### ISSUE TITLE
Please be clear that FriendlyCaptcha isn't entirely open source

### ISSUE THREAD

**Issue by TheEvilSkeleton** [FriendlyCaptcha/friendly-challenge#10]
Hi, after doing a bit of research, I've realized that FriendlyCaptcha isn't entirely open source.

> ## Alternatively, do it yourself
> FriendlyCaptcha is open source allowing you to build out this service yourself.

https://friendlycaptcha.com/

> Its front-end and algorithms are open source (MIT), the SaaS wrapper around the hosted version is not [yet, I set it as a sponsorship goal], I hope that’s ok.

https://codeberg.org/swiso/website/issues/133

I will appreciate if the website makes it clear that some bits are proprietary.

**Comment by dev-love** [comment]
Hi @TheEvilSkeleton!
We are currently working on our new website, which will make clear that Friendly Captcha is not only developing open source code, but also a service provider.
Looking forward to the potential integration of Friendly Captcha into swiso!
