### ISSUE TITLE
Best Content Security Policy (CSP) allowing widget?

### ISSUE THREAD

**Issue by gioypi** [FriendlyCaptcha/friendly-challenge#100]
Is there a way to whitelist FriendlyCaptcha in the _default-src_ and _script-src_ fields of a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), in order to limit other scripts without breaking functionality?
I tried using friendlycaptcha.com and unpkg.com as exceptions to the policy, but the widget cannot load.
Thanks!

**Comment by merlinfuchs** [comment]
This should work:
```xml
 <meta
      http-equiv="Content-Security-Policy"
      content="child-src blob:; default-src 'self' *.friendlycaptcha.eu *.friendlycaptcha.com; script-src 'self' unpkg.com blob:"
    />
```

**Comment by gioypi** [comment]
Interestingly, this brings back functionality, but breaks the way the widget renders. Instead of the rectangle window, the elements of the widget fall in the parent's css.

**Comment by merlinfuchs** [comment]
Ah yeah, you need to add `'unsafe-line'` to the `default-src`.

**Comment by gioypi** [comment]
You mean `'unsafe-inline'`, yes that did the trick! Mozilla Observatory does not complain too much about this CSP.
Thank you very much!
