### ISSUE TITLE
Issue with Edge Browser Strict Mode

### ISSUE THREAD

**Issue by dev-love** [FriendlyCaptcha/friendly-challenge#102]
Hi FriendlyCaptcha Team,

Today I noticed, that the captcha on my site does not finish loading anymore and is stuck after about 10%.
I looked into the dev console and noticed the following error:
FriendlyCaptcha failed to initialize WebAssembly, falling back to Javascript solver: ReferenceError: WebAssembly is not defined

But even falling back to javascript did not solve any issue.

I remembered that I had a similar issue with another webapp. The issue here is, this security mode in the Microsoft Edge Browser:
https://share.zkr.io/img/xZvr4.png

When this is disabled or a exception is made for the website using FriendlyCaptcha, there is no issue. But when this mode is enabled FriendlyCaptcha does not work at all.
I assume that this will be hard for you to solve, since Edge blocks WebAssembly which now powers more and more WebApps. But the issue is, that for a normal user it is hard to find out why FriendlyCaptcha does not work.
Maybe it would be enough to add a hint to the captcha application, that the user should try to disable this setting within the browser, when WebAssembly fails to load.

Please let me know, if you have any further questions.

**Comment by gzuidhof** [comment]
Ah, I'm quite surprised that a strict mode would simply disable all WebAssembly. The fallback solver seems to not work here, definitely something we should reproduce and resolve.

If it turns out it's impossible to resolve, we should at the very least warn the user - but I'm sure the JS fallback could work.

**Comment by gzuidhof** [comment]
I believe we have not run into this again. If `WebAssembly` is indeed undefined, there is not much we can do. The widget does the right thing by switching back to the JS solver.
