### ISSUE TITLE
Turkish language support

### ISSUE THREAD

**Issue by selim995** [FriendlyCaptcha/friendly-challenge#103]
Hi,

Can you add Turkish language support? I translated for you.

// Turkish
const LANG_TR: Localization = {
  text_init: "Başlatılıyor..",

  text_ready: "Anti-Robot Doğrulaması",
  button_start: "Doğrulamayı başlatmak için tıklayın",

  text_fetching: "Yükleniyor",

  text_solving: "Robot olmadığınız doğrulanıyor..",
  text_completed: "Ben bir insanım",
  text_completed_sr: "Otomatik spam kontrolü tamamlandı",

  text_expired: "Anti-Robot doğrulamasının süresi doldu",
  button_restart: "Yeniden başlat",

  text_error: "Doğrulama başarısız oldu",
  button_retry: "Tekrar dene",
  text_fetch_error: "Bağlantı başarısız oldu",
};

export const localizations = {
  tr: LANG_TR,
};

**Comment by gzuidhof** [comment]
Thank you for the translation! It's now part of the library in version `0.9.3` :)
