### ISSUE TITLE
How can I make FriendlyCaptcha a required field?

### ISSUE THREAD

**Issue by abidi12** [FriendlyCaptcha/friendly-challenge#104]
I'm using FriendlyCaptcha and have been able to add the CAPTCHA component to my page inside a form. But when I submit the form there's no validation taking place to check if the CAPTCHA has been solved.

`<!– Add the widget script –>
 <script type="module" src="https://cdn.jsdelivr.net/npm/friendly-challenge@0.9.2/widget.module.min.js" async defer></script>
<script nomodule src="https://cdn.jsdelivr.net/npm/friendly-challenge@0.9.2/widget.min.js" async defer></script>

<div class="frc-captcha" data-sitekey="FCMV995O03V7XXXXX"></div> `

How do I validate that the CAPTCHA component has been solved when submitting my form? Or, in other words, how do I make my CAPTCHA component required? (using javascript)

**Comment by gzuidhof** [comment]
The most pragmatic approach is generally to enable the submit button of your form in the `doneCallback` or `errorCallback`, that way users won't accidentally submit without the widget done solving.
