### ISSUE TITLE
How to stop auto-start?

### ISSUE THREAD

**Issue by kenw232** [FriendlyCaptcha/friendly-challenge#107]
As soon as the user starts to fill in the form Friendly Captcha auto-starts to solve the problem.  How can I stop this?  I want the user to expressly click it to start it?

**Comment by merlinfuchs** [comment]
Set the `data-start` attribute on the widget to `none`.
You can find the documentation here: https://docs.friendlycaptcha.com/#/widget_api?id=data-start-attribute
