### ISSUE TITLE
Bug renders retry button unusable

### ISSUE THREAD

**Issue by davidbeermann** [FriendlyCaptcha/friendly-challenge#108]
The PR https://github.com/FriendlyCaptcha/friendly-challenge/pull/90 introduced an `if` condition which can render the widget's retry button unusable. Once clicked the console logs the expected message: `Can not start FriendlyCaptcha widget which has already been started` – see here https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/captcha.ts#L193-L196. However, in case of the retry button this message makes no sense when an error lead to the retry state and the button should actually _re-start_ the widget.

## Steps to reproduce the faulty behavior

* Clone/Checkout the Next.js example from https://github.com/FriendlyCaptcha/friendly-captcha-examples and navigate to project via `cd nextjs`
* Upgrade the `friendly-challenge` package to the latest version: `npm i friendly-challenge@0.9.2`
* Start the dev server via `npm run dev`
* Open the local server url in Chrome and navigate to the basicform example http://localhost:3000/forms/basic
* Verify that CAPTCHA behaves as expected
* Open Chrome's Developer Tools and use the [Network Request Blocking tab](https://developer.chrome.com/docs/devtools/network/#block) to block all requests to the default puzzle endpoint `api.friendlycaptcha.com/api/v1/puzzle`. This simulates an outage on Friendly Captcha's side.
* Reload the page, request a CAPTCHA puzzle and confirm that the error message `[FriendlyCaptcha]: TypeError: Failed to fetch` is output to the console and the retry button is rendered. Upon clicking the retry button confirm that the warning is logged to the console and that the retry button is never fetching another puzzle.

If oyu like you can also downgrade to version `0.9.1` via `npm i friendly-challenge@0.9.1` to confirm that the widget works as expected.

## Possible work-around

Depending on the `startMode` of the widget one solution could be to reset the widget upon error. In the example mentioned above this could be done by changing the error callback as follows:
```jsx
        <FriendlyCaptcha
          ref={widgetRef}
          sitekey={process.env.NEXT_PUBLIC_FRIENDLY_CAPTCHA_SITEKEY}
          doneCallback={() => setSubmitButtonEnabled(true)}
          errorCallback={(err) => {
            setMessage("Anti-robot widget issue" + JSON.stringify(err)); // Should really never happen.
            // setSubmitButtonEnabled(true); <-- This line was commented out
            reset(); // <-- This line was added
          }}
        ></FriendlyCaptcha>
```

While this works for `startMode` `none` and `focus` it yields a very odd behavior for `auto`.
```jsx
        <FriendlyCaptcha
          ref={widgetRef}
          sitekey={process.env.NEXT_PUBLIC_FRIENDLY_CAPTCHA_SITEKEY}
          doneCallback={() => setSubmitButtonEnabled(true)}
          errorCallback={(err) => {
            setMessage("Anti-robot widget issue" + JSON.stringify(err)); // Should really never happen.
            // setSubmitButtonEnabled(true); <-- This line was commented out
            reset(); // <-- This line was added
          }}
          startMode="auto" // <-- This line was added
        ></FriendlyCaptcha>
```

Then, the inital widget state is rendered and flickers back and forth between loading and init state.

Since my company is working with `startMode` `auto` we decided to pin version `0.9.1` until this issue is solved.

**Comment by gzuidhof** [comment]
Thank you for the detailed report, this is definitely something that should be fixed. Could you please have a look at this @merlinfuchs?
