### ISSUE TITLE
WidgetInstanceOptions interface is not exported

### ISSUE THREAD

**Issue by davidbeermann** [FriendlyCaptcha/friendly-challenge#109]
While the TypeScript declaration for `WidgetInstance` is exported this is not the case for the declaration of `WidgetInstanceOptions`.

AFAIK, it's accepted best practice to export all declarations of a package to prevent re-declaring types when building wrapping functions/components/abstractions around the `friendly-challenge` package. A good example (if the [nextjs example](https://github.com/FriendlyCaptcha/friendly-captcha-examples) was written in TypeScript) is to inherit the type for `startMode` within the `FriendlyCaptcha` props. This could look something like this:

```ts
export type FriendlyCaptchaProps = Partial<Pick<WidgetInstanceOptions, 'startMode'>> & {
    // your component's props...
}
```

This way it's ensured that for example breaking changes to `startMode` would automatically be detected throughout the code base which is not the case if one were to copy parts of the declaration like so:

```ts
export type FriendlyCaptchaProps = {
    startMode?: "auto" | "focus" | "none"
}
```

**Comment by gzuidhof** [comment]
Ah this is something we should be able to fix, it's not excluded on purpose (I'm happy to export all internal types). We're using the `dts` plugin for Rollup [here](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/rollup.library.config.ts#L70-L72), we can probably somehow convince it to export more than just `WidgetInstance`. I think it's just a matter of exporting the type [here](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/index.ts#L1). I'll give it a shot, thank you for the suggestion

**Comment by gzuidhof** [comment]
PR #111 seeks to solve this issue, could you have a look @davidbeermann? https://github.com/FriendlyCaptcha/friendly-challenge/pull/111 

For a bit of background why we don't just use the TS compiler (so we always get the right typings) is because our  build process is [quite involved](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/package.json#L18-L29) to support every browser under the sun.

**Comment by davidbeermann** [comment]
@gzuidhof I looked at the PR. Looks good to me. 👍  The new build output definitely solves the issue raised here.
