### ISSUE TITLE
Missing (unit) tests?

### ISSUE THREAD

**Issue by davidbeermann** [FriendlyCaptcha/friendly-challenge#110]
This is more a question than an issue as I'm not sure how you internally ensure the quality of the package releases. But while looking into issue https://github.com/FriendlyCaptcha/friendly-challenge/issues/108 I noticed the absence of tests for this package.

As I'm not aware if you as maintainers keep these tests private in a separate repo I see the current absence as a problem because for my team as consumers of this package we do not test the widget itself. Instead we just test our integration code and tend to mock the `friendly-challenge` package. Therefore, in case of the update from version `0.9.1` to `0.9.2` the implied breaking change by the bug outlined above would have gone unnoticed if not for extensive manual testing. Since the bug above is internal to the widget it's also unlikely that any other tests (e.g. End-to-end tests) would have caught it.

Hence my question, what is the reason that there are no unit tests for this package? How do you ensure that changes to the package do not yield unexpected side effects to the consumers of it?

**Comment by gzuidhof** [comment]
This is very fair feedback, our testing story could be improved for sure. This widget grew from a trivial implementation (which had unit tests within this same repo) to something more complex as we aimed to make it easy to fit into any web project.

The internal workings (i.e. the actual algorithm) is tested [here](https://github.com/FriendlyCaptcha/friendly-pow/tree/master/test), but the widget at large is not tested end to end as I would like.

We perform testing with various real devices using BrowserStack, but that is mostly to test for correct functioning across rather old devices and browsers (and it's mostly manual, that comes with the territory). We do not have a test for intermittent connection failures which is definitely to be improved. With the way the widget is designed it's hard to test separate from the backend, making it the pragmatic choice for us not to include the tests here.

We are working on version 2 of the captcha and widget which takes our learnings over the past years and applies them, one of them is the ability to truly test end to end (as well as a more sandboxed approach that will prevent interop issues). The widget in this repo won't see any big changes anymore (I presume) and has reached a state of (almost) correctness with the fix in #112. 

I hope that answers your question.. it's not the perfect answer but it is the reality right now. I'll close this issue for now but feel free to re-open at a later time
