### ISSUE TITLE
Script injection does not account for async rendering

### ISSUE THREAD

**Issue by davidbeermann** [FriendlyCaptcha/friendly-challenge#114]
Upon the instantiation of the `WidgetInstance` class [the injection of the widget's style happens synchronously](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/captcha.ts#L107). This creates a problem for example in a Next.js application where you'd want to co-locate your custom styling with your component and inject the custom styling via e.g. [react-helmet-async](https://github.com/staylor/react-helmet-async). The components return value would look like this:

```jsx
        return (
            <>
                <Helmet >
                    <link rel="stylesheet" id="frc-style" href="/frc-widget-theme.css" />
                </Helmet>
                <div
                    ref={captchaRef}
                    id="frc-captcha"
                    className="frc-captcha"
                />
            </>
        )
```

With the current version of the `WidgetInstance` class this leads to two style definitions for the widget being added to the document's `<head>`: first the sychronous injection of the `<style>` element of the instance and then secondly the asynchronous injection of the `<link>` element via `react-helmet-async`. This then leads to broken custom widget styles. The only solution right now is not to co-locate custom styles with the widget and add the widget's custom styles statically to the rendered document.

One quick solution to the issue I could see to this is to make the injection of the widget's style optional via the `WidgetInstanceOptions` and yield the full control over the widget's style to the package consumer. I haven't spend too much time thinking about whether that's the best option though. 🤔

**Comment by merlinfuchs** [comment]
A workaround would be to just create an empty element with the `frc-style` id yourself. The library should then skip the style injection.
I think this is a common problem across many libraries. For example to make fontawesome work correctly with nextjs you have to disable the style injection like this and then import the stylesheet yourself.
```js
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;
```

**Comment by davidbeermann** [comment]
> A workaround would be to just create an empty element with the frc-style id yourself. The library should then skip the style injection.
@merlinfuchs True, that would work as well. It's a little hacky though as this means I'll have prevent the injection based on an implementation detail within the package that I have no control over. This tight coupling would be prevented by making the injection configurable – like you also suggested in the example above. IMO that's the better solution to the problem.
