### ISSUE TITLE
Failed to connect to

### ISSUE THREAD

**Issue by mfeske** [FriendlyCaptcha/friendly-challenge#121]
Hello everyone, I've tried to integrate friendlycaptcha into my PHP script according to the instructions [1]. I also created a sitekey and pass that with the div. However, I keep getting the error "Verification failed
Failed to connect to" {
"success": false,
"errors": [
"sitekey_missing"
]
} url_fopen is on though. [1] https://docs.friendlycaptcha.com/#/installation

**Comment by mfeske** [comment]
Message from console:
VM101:1          GET https://api.friendlycaptcha.com/api/v1/puzzle?sitekey=FCMG0BQEP7DBPAPV 403
(anonymous) @ VM101:1
l @ widget.module.min.js:1
(anonymous) @ widget.module.min.js:1
start @ widget.module.min.js:1
e @ widget.module.min.js:1
widget.module.min.js:1 [FriendlyCaptcha]: Error: Endpoint not allowed (403)
    at widget.module.min.js:1:27927
    at async I.start (widget.module.min.js:1:27617)

**Comment by merlinfuchs** [comment]
I don't know PHP but this looks a lot like a GET request
```php
$request = file_get_contents('https://api.friendlycaptcha.com/api/v1/siteverify?secret=' . friendlycaptchaKEYSECRET . '&sitekey=' . friendlycaptchaKEYPUBLIC . '&solution=' . $_POST['frc-captcha-solution']);
```

**Comment by merlinfuchs** [comment]
> VM101:1 GET https://api.friendlycaptcha.com/api/v1/puzzle?sitekey=XXX 403
(anonymous) @ VM101:1
l @ widget.module.min.js:1
(anonymous) @ widget.module.min.js:1
start @ widget.module.min.js:1
e @ widget.module.min.js:1
widget.module.min.js:1 [FriendlyCaptcha]: Error: Endpoint not allowed (403)
at widget.module.min.js:1:27927
at async I.start (widget.module.min.js:1:27617)

This indicates that you have the global endpoint disabled in your application. Please check in the Friendly Captcha dashboard which endpoints you have enabled for your application.
