### ISSUE TITLE
Puzzle expiry timeout not removed after widget destroy/complete

### ISSUE THREAD

**Issue by lakeboerg** [FriendlyCaptcha/friendly-challenge#123]
### Introduction

Dear FriendlyCaptcha fellows,

firstly, thanks a lot to you and your services - I am a happy customer and enjoy using FriendlyCaptcha 🎉

### Issue

During captcha start, the puzzle expiry timeout is set.

https://github.com/FriendlyCaptcha/friendly-challenge/blob/a15c556b0fb8ca4ca8ed3e0c747c5f1178e4049d/src/captcha.ts#L232-L251

If no page-load occurs after the captcha completed (successfully, or not), the expire functionality is invoked regardless.

In case the captcha widget is removed after usage (e.g. XHR submission because in SPA or just UX), this causes errors as the captcha's DOM node is not present anymore.

### Solution proposal

You will come up with the most fitting solution anyways. Yet my most likely very wrong 2 cents:
Clear the timeout when the captcha is destroyed (and other potential use-cases).

### Steps to reproduce

1. Embed captcha in page with working configuration
2. Open page and start captcha
3. Remove captcha after completion by e.g. removing the parent DOM node
4. Wait for puzzle timeout to occur (better: use a low expiry ;) )
5. Check console

**Question**
Do you prefer a PR over an issue? Just let me know, thanks a lot upfront!

My first GitHub issue, so jn case it's utterly wrong, sorry already 😅

**Comment by gzuidhof** [comment]
Thank you for the issue, congrats on your first GH issue! It's really well done :)

I agree this should be fixed, most users won't run into it as the expiry time is fairly long (measured in hours) and the errors are not visisble to end users. But definitely let's fix this!

I think the straightforward fix is to keep the return value from `setTimeout` in a field, and use `clearTimeout` whenever:
 * An error occurs
 * `destroy()` or `reset()` is called.
 * Just before the setTimeout is called (cleaning up prior calls to it, currently they could overlap)
 
And in the `expire()` function we could doublecheck that the element is still mounted, just to be on the safe side (I can see a lot of implementations not calling `destroy()` correctly - let's cut them some slack :))

**Comment by lakeboerg** [comment]
Thanks for the swift reply.

Yep, that solution makes sense and should cover all use-cases.

So, the question of all questions: Will you pick it up?

**Comment by gzuidhof** [comment]
@merlinfuchs would you be up for owning this? If your availability isn't great I can own it instead :)

**Comment by gzuidhof** [comment]
Just following up here as there hasn't been much activity, is this actively causing issues or is it also OK if we only get around to this in say a month's time (e.g. it only puts some error messages in the console but the user would never notice)?

In other words I'm proposing to keep this fix as low priority for now (any open source contributor feel free to pick it up in the meantime of course!).
