### ISSUE TITLE
SiteKey/SecretKey invalid

### ISSUE THREAD

**Issue by SunithaBabu04** [FriendlyCaptcha/friendly-challenge#126]
Hi,

I am a new user of FriendlyCaptcha.

I could successfully verify the captcha if the solution, secret and sitekey are correct.

I am trying to test by passing invalid secret key/sitekey, it is working fine in postman and give me the response as 
{
    "success": false,
    "errors": [
        "sitekey_invalid"
    ]
}
but when I try the incorrect values from backend,
for incorrect secret key , I get a webexception as Unauthorised
for incorrect sitekey , I get a webexception as Bad request

**Comment by merlinfuchs** [comment]
As documented here https://docs.friendlycaptcha.com/#/verification_api?id=the-verification-response you may receive a 401 (Unauthorized) when the sitekey is missing and a 400 (Bad Request) the sitekey is invalid.
Some HTTP libraries will raise an exception when they receive such a status code. That's not specific to Friendly Captcha tho
