### ISSUE TITLE
selenium test failes

### ISSUE THREAD

**Issue by lj-n** [FriendlyCaptcha/friendly-challenge#130]
Hi,

We are using the friendly-challenge Widget in our React forms and everything works great so far!

We like to run selenium tests to ensure that our forms work. As [described in the docs](https://docs.friendlycaptcha.com/#/automated_testing?id=dynamic-button-enabling), we use a mocked API and enable the submit button during the test.

Now during the tests, when the form is submitted, the page reloads with the url params `?frc-captcha-solution=.UNSTARTED`

Do you have any information on this? I couldn't find any other issue or docs related to this.

Thank you for this great tool!

**Comment by gzuidhof** [comment]
I imagine this is the plain HTML form submitting. When you have a `<form>` element and put a submit button inside of it, by default it makes a request to the same URL with the form fields encoded as URL parameters.

As you are using React, you likely are sending the form's data using Fetch or XMLHttpRequest. In that case you would usually disable the default behavior by calling `event.preventDefault()`

I hope that helps figure out the solution :) If not, feel free to comment again!
