### ISSUE TITLE
Make Browser Check Text Configurable

### ISSUE THREAD

**Issue by dev-love** [FriendlyCaptcha/friendly-challenge#140]
The error text "Browser check failed, try a different browser" can currently not be configured in the widget (like the other displayed texts otherwise). Could this text also be stored in a text key in the future?

**Comment by merlinfuchs** [comment]
The text should only be visible when using an automated browser like Selenium. Normal users shouldn't ever encounter this in theory. The only case that I can think of where a non attacker ever sees this text is automated testing of the integration 🤔 
I think we could just display the `Verification failed` text which is already localized and log something to the console instead

**Comment by andreasstreng** [comment]
@gzuidhof : It's not correct to say "Normal users shouldn't ever encounter this". 

For Example: after installing the Browser-Plugin "ruffle" the user will see "Browser check failed, try a different browser".
Please reopen this ticket and make the browser check message configurable.
Thx
Andi
<img width="1155" alt="Bildschirmfoto 2022-10-10 um 12 50 06" src="https://user-images.githubusercontent.com/10449924/194850070-2b502550-1edf-4f6a-8fa3-1d41794cad70.png">
