### ISSUE TITLE
Example for Selenium Integration

### ISSUE THREAD

**Issue by dlitmano** [FriendlyCaptcha/friendly-challenge#142]
Hello FriendlyCaptcha,

we use your Captcha for our Website. But If I run my e2e tests, always the same message "Browser check failed, try a different browser".

Do you have a standard example to disable Captchas? (e.g. https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do)

Greets
Dimi

**Comment by gzuidhof** [comment]
Hi Dimi,

We have a docs page that should help: https://docs.friendlycaptcha.com/#/automated_testing, the short version is that the best way forward is to disable the captcha check on the backend with a flag when you are running your tests.
