### ISSUE TITLE
Provide a GitHub release (build / dist)

### ISSUE THREAD

**Issue by JPustkuchen** [FriendlyCaptcha/friendly-challenge#143]
Hi FriendlyCaptcha Team,

we're maintaining the Drupal FriendlyCaptcha module (https://www.drupal.org/project/friendlycaptcha) and wanted to document manual installation, if someone is not using npm or composer (via NPM). Sadly it seems the widget.min.js is not available without NPM for manual download / installation.

Could you perhaps either
a) Provide a link in the documentation and on the GitHub page directing to the widget.min.js latest version download
or
b) Use [GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) to provide the dist for download?
or 
c) both?

That would be great and very helpful. Perhaps there's a smooth option for something like this in the build pipeline?

**Comment by gzuidhof** [comment]
Hi Julian,

You should be able to download the built files directly from CDNs that serve NPM files. For instance [here](https://cdn.jsdelivr.net/npm/friendly-challenge/) through JSDelivr. Would that solve this?

**Comment by mimenz** [comment]
Hi there,

would it be possible to release a compressed version of the default style sheet, too?
E.g. widget-0.9.7.min.css

Currently I have to look up the file content and compress it for myself - or is there a place I don't know?

**Comment by gzuidhof** [comment]
> Hi @gzuidhof,
> 
> yes indeed, that was meant with option (a) perhaps you could simply pot a download link for the module & non-module version into the README.md file, so it's displayed for users who are not experienced with NPM?
> 
> It could even have the HTML5 download attribute perhaps: https://www.w3schools.com/tags/att_a_download.asp
> 
> I think that might be a good (documentation) alternative to the release option (b).

Sure! Happy to accept a PR with links where you think it makes sense :) You can point them to the latest version, upon every release I manually bump them (cmd+F goes a long way here).

**Comment by gzuidhof** [comment]
> Hi there,
> 
> would it be possible to release a compressed version of the default style sheet, too? E.g. widget-0.9.7.min.css
> 
> Currently I have to look up the file content and compress it for myself - or is there a place I don't know?

Currently we build the CSS file and then immediately inject it into code, it never lives as a file. Of course that is possible to change, but seeing as it's changing very infrequently and very few people end up incorporating the CSS file manually, you could perhaps use JSDelivr to download the two versions?

https://cdn.jsdelivr.net/gh/friendlycaptcha/friendly-challenge@master/src/styles.css
(The below one gets auto-generated by JSDelivr itself)
https://cdn.jsdelivr.net/gh/friendlycaptcha/friendly-challenge@master/src/styles.min.css

**Comment by mimenz** [comment]
> > Hi there,
> > would it be possible to release a compressed version of the default style sheet, too? E.g. widget-0.9.7.min.css
> > Currently I have to look up the file content and compress it for myself - or is there a place I don't know?
> 
> Currently we build the CSS file and then immediately inject it into code, it never lives as a file. Of course that is possible to change, but seeing as it's changing very infrequently and very few people end up incorporating the CSS file manually, you could perhaps use JSDelivr to download the two versions?

I suppose you're talking about the case in which the website takes the widget from jsdelivr?
We're hosting the Friendly Captcha files for ourselves - but in this case I also have to provide the css file to get the styled widget - correct?

> 
> https://cdn.jsdelivr.net/gh/friendlycaptcha/friendly-challenge@master/src/styles.css (The below one gets auto-generated by JSDelivr itself) https://cdn.jsdelivr.net/gh/friendlycaptcha/friendly-challenge@master/src/styles.min.css

Thanks for the last link, didn't know about it. That's sufficient for me.

**Comment by gzuidhof** [comment]
> I suppose you're talking about the case in which the website takes the widget from jsdelivr?
We're hosting the Friendly Captcha files for ourselves - but in this case I also have to provide the css file to get the styled widget - correct?

The CSS is also present in the JS file as a string, and it will add it to the `head` of the document unless you tell it not to (e.g. if you want to provide your own style, or if you have strict CSP settings that require it). In other words, usually you won't have to :)

**Comment by JPustkuchen** [comment]
> > Hi @gzuidhof,
> > yes indeed, that was meant with option (a) perhaps you could simply pot a download link for the module & non-module version into the README.md file, so it's displayed for users who are not experienced with NPM?
> > It could even have the HTML5 download attribute perhaps: https://www.w3schools.com/tags/att_a_download.asp
> > I think that might be a good (documentation) alternative to the release option (b).
> 
> Sure! Happy to accept a PR with links where you think it makes sense :) You can point them to the latest version, upon every release I manually bump them (cmd+F goes a long way here).

Here we go: https://github.com/FriendlyCaptcha/friendly-challenge/pull/149
