### ISSUE TITLE
FriendlyCaptcha isn't rendering on the UI in Nextjs

### ISSUE THREAD

**Issue by dhavalveera** [FriendlyCaptcha/friendly-challenge#145]
Hello,

```js
import { useEffect, useRef } from 'react';
import { WidgetInstance } from 'friendly-challenge';

const FriendlyCaptcha = () => {
  const container = useRef();
  const widget = useRef();

  useEffect(() => {
    if (!widget.current && container.current) {
      widget.current = new WidgetInstance(container.current, {
        startMode: 'auto',
      });
    }

    return () => {
      widget.current.destroy();
      widget.current = null;
    };
  }, [container]);

  return (
    <div
      ref={container}
      className='frc-captcha'
      data-sitekey='YOUR_SITE_KEY'
    />
  );
};

export default FriendlyCaptcha;
```

```js
import { useEffect, useRef } from 'react';
import { WidgetInstance } from 'friendly-challenge';

const FriendlyCaptcha = () => {
  const container = useRef();
  const widget = useRef();

  const doneCallback = (solution) => {
    console.log('Captcha was solved. The form can be submitted.');
    console.log(solution);
  };

  const errorCallback = (err) => {
    console.log('There was an error when trying to solve the Captcha.');
    console.log(err);
  };

  useEffect(() => {
    if (!widget.current && container.current) {
      widget.current = new WidgetInstance(container.current, {
        startMode: 'auto',
        doneCallback: doneCallback,
        errorCallback: errorCallback,
      });
    }

    return () => {
      if (widget.current != undefined) widget.current.destroy();
    };
  }, [container]);

  return (
    <div
      ref={container}
      className='frc-captcha'
      data-sitekey='YOUR_SITE_KEY'
      data-start='auto'
    />
  );
};

export default FriendlyCaptcha;
```

I tried both code snippets, but not either one is rendering the FriendlyCaptcha on the UI in Nextjs.

**Comment by merlinfuchs** [comment]
The issue seems to be caused by the `widget.destroy` in the `useEffect` cleanup. Since React 18 `useEffect` hooks are called multiple times in dev mode (https://medium.com/geekculture/the-tricky-behavior-of-useeffect-hook-in-react-18-282ef4fb570a). In production this issue shouldn't appear.
I think it depends on your use-case if you want to keep the `widget.destroy` call in the cleanup function.

**Comment by dhavalveera** [comment]
> The issue seems to be caused by the `widget.destroy` in the `useEffect` cleanup. Since React 18 `useEffect` hooks are called multiple times in dev mode (https://medium.com/geekculture/the-tricky-behavior-of-useeffect-hook-in-react-18-282ef4fb570a). In production this issue shouldn't appear. I think it depends on your use-case if you want to keep the `widget.destroy` call in the cleanup function.

@merlinfuchs  === Thanks, I removed the `widget.destory()` from the `useEffect()` cleanup function, now FriendlyCaptcha is working perfectly fine.

Thanks a lot...

based on the Privacy + EU Compliances I'm preferring FriendlyCaptcha compared to Google reCaptcha & hCaptcha.

again Thanks
