### ISSUE TITLE
@gzuidhof : It's not correct to say "Normal users shouldn't ever encounter this".

### ISSUE THREAD

**Issue by andreasstreng** [FriendlyCaptcha/friendly-challenge#147]
@gzuidhof : It's not correct to say "Normal users shouldn't ever encounter this". 

For Example: after installing the Browser-Plugin "ruffle" the user will see "Browser check failed, try a different browser".
Please reopen this ticket and make the browser check message configurable.
Thx
Andi
<img width="1155" alt="Bildschirmfoto 2022-10-10 um 12 50 06" src="https://user-images.githubusercontent.com/10449924/194850070-2b502550-1edf-4f6a-8fa3-1d41794cad70.png">

_Originally posted by @andreasstreng in https://github.com/FriendlyCaptcha/friendly-challenge/issues/140#issuecomment-1273130943_

**Comment by gzuidhof** [comment]
Thank you for reporting this issue, we should make changes to make that statement true again. 

I imagine that "Ruffle" changes something w.r.t. to the plugin array/prototypes - that seems like something we should change (or remove): https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/headless.ts#L17-L19. Until now I haven't been able to reproduce this issue - but now I can. I'll pick this up and see if I can make the required changes this afternoon.

**Comment by gzuidhof** [comment]
This should be fixed in version `0.9.8` of the widget, let me know if you still run into this error after updating to that version.

**Comment by gzuidhof** [comment]
A bit of background: 

This testing page (unrelated to Friendly Captcha) that attempts to client-side detect headless browsers also shows as a false positive. I imagine this signal is no longer a trustworthy indicator for headless browsers (which is fine, things are ever-changing) - so we will remove it. Thank you again for bringing this to our attention.

In Firefox (without Ruffle)

![Screenshot 2022-10-10 at 13 58 06](https://user-images.githubusercontent.com/1039510/194861306-e37b7e44-4ac7-4bc7-9853-c18f25e4e764.png)


In Brave with Ruffle installed
<img width="554" alt="Screenshot 2022-10-10 at 13 58 57" src="https://user-images.githubusercontent.com/1039510/194861414-aada1fc7-c135-48fb-a149-d819c8cc014d.png">
