### ISSUE TITLE
app id does not match

### ISSUE THREAD

**Issue by WD-SGR** [FriendlyCaptcha/friendly-challenge#155]
I'm trying to integrate friendly challenge into an Angular application. As long as no second site is loaded, friendly captcha works just fine. As soon as you switch to a second site it no longer works as expected. Puzzles are still created and theire solutions looks normal. However, if you try to validate them via the siteverify endpoint the response is always `{"success":false,"errors":["solution_invalid"],"details":"app id does not match"}`. If you reload the page (with cache refresh or without cache refresh does not matter) the verification process works again. I've tried to find a solution for this, but failed, so far. What does "app id does not match" mean? Is the error related to the API key (and then why would it work after a site refresh)? 

I suspect it may have something to do how the widget is destroyed and later recreated. Maybe something stays in the browser? I tried to call this.widget.destroy(); in ngOnDestroy(). It did not make any difference.

**Comment by merlinfuchs** [comment]
You get this error when the puzzle solution provided in your request to the `/siteverify` endpoint belongs to a different sitekey then the sitekey that you have provided in the request. If you provide the `sitekey` field in the request to the `/siteverify` endpoint it has to match with the puzzle solution.

**Comment by WD-SGR** [comment]
Thank you for the quick response. We could fix the angular implementation now! Indeed we generated puzzles with another sitekey that was still in the angular store (saved in browser store) and we checked with /siteverify with the actual sitekey . We delete the particular store now everytime the widget is destroyed.
