### ISSUE TITLE
Server-side integration

### ISSUE THREAD

**Issue by alkacon-jGraf** [FriendlyCaptcha/friendly-challenge#161]
Dear Friendly Captcha Team,

we are currently developing a Friendly Captcha integration for one of our customers. Is it possible to realize a fully server-side integration where the browser does not call any Friendly Captcha service endpoint directly?

As far as we can see, we can host the widget's JavaScript on our own server. The documentation also says that we can verify puzzle solutions on the server side.

What is about the puzzle endpoint? Is there anything against sending the browser's puzzle request to our own server at first which then forwards the puzzle request to the Friendly Captcha service endpoint? 

If using our own server as a "proxy" between Browser and the Friendly Captcha service endpoint is technically possible and recommended from your side: would this really mean that no direct communication between Browser and your service endpoints takes place?

Thank you very much for your help!

**Comment by gzuidhof** [comment]
Hi alkacon-jGraf,

Yes and no, it depends (like everything ^^). Some customers of ours do proxy puzzle requests from the browser through their own servers, and that's ok. You lose some benefits, and we lose the ability to properly do our smart difficulty scaling. One of the main levers we have is the ability to determine how difficult the puzzle should be for a given visitors which is something that is lost.

But then I understand that for some businesses there are other considerations at play that weigh more heavily which makes getting to zero third party requests desirable, you are probably the best judge if that is the case for your usecase.

So the short answer is: yes you can proxy through your own server, but the protection will be weakened in such a setup.

I hope that makes sense, do let me know if you have any follow-up questions.

**Comment by alkacon-jGraf** [comment]
Thank you very much for your fast reply and the detailed information which will help our customer to make his decision.
