### ISSUE TITLE
friendly-challenge breaks with Next.js 13 & prod build mode

### ISSUE THREAD

**Issue by jablonski** [FriendlyCaptcha/friendly-challenge#165]
We run into trouble with FriendlyCaptcha & prod build in Next.js 13. Our implementation worked fine in Next 12 (in dev & build). The problem exists only in "build mode" for Next 13, "dev mode" is also fine with Next 13.

We've used the starter (https://github.com/FriendlyCaptcha/friendly-captcha-examples/tree/main/nextjs), upgraded it to Next 13 and see the problems there too.

What we did find... the provided solution on the input field looks far to short in Next 13 in build mode.

In **Next 13 / Dev-Mode** we see this:

`<input name="frc-captcha-solution" class="frc-captcha-solution" type="hidden" value="2fd3a588a8bbc92d01486d58de4bd1ec.Y353FY0rviTOdl28AQwtjQAAAAAAAAAAyUtByvsNzgI=.AAAAAE2sAgABAAAAyV8AAAIAAADQaAIAAwAAACi8AAAEAAAAUS0BAAUAAACeHQEABgAAAOSNAQAHAAAAWq4BAAgAAACT4AEACQAAAOzbAAAKAAAAKYYDAAsAAAAwGAUADAAAAHgpAQANAAAAUcwBAA4AAACXlwEADwAAAC6DAQAQAAAAg2gDABEAAACw2wEAEgAAAHunBAATAAAAK3kBABQAAAANEgMAFQAAACTWAwAWAAAAwGMAABcAAAAUrgAAGAAAAHvVAgAZAAAAZ2YIABoAAADUAQIAGwAAAGyVAAAcAAAARf4BAB0AAAAkDgAAHgAAADxHAAAfAAAAdCcAACAAAAAOZgIAIQAAANZJDwAiAAAA01cFACMAAADEJgUAJAAAAE2MAAAlAAAA3WMHACYAAADvNQAAJwAAAI67AQAoAAAAJtAFACkAAAA4jAgAKgAAABrQAgArAAAAtykFACwAAADxZwAA.AgAB">`

In **Next 13 / Build-Mode** the result is:

`<input name="frc-captcha-solution" class="frc-captcha-solution" type="hidden" value="683c27975406749fb89afdf8ddee3a19.Y353NY0rviTOdl28AQwtjQAAAAAAAAAAEgozXZpAXRg=.uQIA.AgAB">`

Any idea what is the root cause for this issue? We've also tried React 18 and Next 12 which works fine.

**Comment by gzuidhof** [comment]
Hi @jablonski,

I'm not entirely sure what could possibly be the cause of this from first glance, the input field indeed looks  too short - perhaps there is some build step in NextJS that is an issue for this library that we can work around?

@merlinfuchs would you perhaps have time to look into this?

**Comment by jablonski** [comment]
The solutions in Dev-Mode are always very much longer than in Prod mode. This is very strange.

If it might help, we can send you our current example via personal mail.

**Comment by gzuidhof** [comment]
Sure that sounds helpful! Could you send it to `guido@` and `merlin@` `friendlycaptcha.com`? 

Alternatively of course a PR is also welcome to the Next example repo if that isn't too much of a hassle

**Comment by jablonski** [comment]
I've created a PR from the example-starter:

https://github.com/FriendlyCaptcha/friendly-captcha-examples/pull/3

**Comment by merlinfuchs** [comment]
I can reproduce the issue with the provided example and will look into it 👍

**Comment by merlinfuchs** [comment]
This issue seems to be in the base64 encoder of the friendly-pow package.
In prod it gets compiled to:
```js
let y = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
      function Q(t) {
        let e = t.length,
          r = "";
        for (let i = 0; i < e; i += 3) {
          console.log(r);
          let o = t[i + 0],
            n = t[i + 1],
            a = t[i + 2];
          r =
            y.charAt(o >>> 2) +
            y.charAt(((3 & o) << 4) | (n >>> 4)) +
            y.charAt(((15 & n) << 2) | (a >>> 6)) +
            y.charAt(63 & a);
        }
        return (
          e % 3 == 2
            ? (r = r.substring(0, r.length - 1) + "=")
            : e % 3 == 1 && (r = r.substring(0, r.length - 2) + "=="),
          r
        );
      }
```
which just overrides r (the result) for every iteration instead of appending to it.

**Comment by jablonski** [comment]
@merlinfuchs Many thanks for looking into this issue, very well spotted.

Quick fix could be to push the strings on an array and .join("") them.

Maybe this would be easier than debugging the issue in the prod bundler.

**Comment by gzuidhof** [comment]
I found a way to convince the compiler not to break the code by introducing a temporary variable..
```typescript
const CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
const EQ_CHAR = "=".charCodeAt(0);
// Use a lookup table to find the index.
const lookup = new Uint8Array(256);
for (let i = 0; i < CHARS.length; i++) {
    lookup[CHARS.charCodeAt(i)] = i;
}
function encode(bytes) {
    const len = bytes.length;
    let base64 = "";
    for (let i = 0; i < len; i += 3) {
        const b0 = bytes[i + 0];
        const b1 = bytes[i + 1];
        const b2 = bytes[i + 2];
        let t = CHARS.charAt(b0 >>> 2);
        t += CHARS.charAt(((b0 & 3) << 4) | (b1 >>> 4));
        t += CHARS.charAt(((b1 & 15) << 2) | (b2 >>> 6))
        t += CHARS.charAt(b2 & 63);
        base64 += t;
    }
    if (len % 3 === 2) {
        base64 = base64.substring(0, base64.length - 1) + "=";
    }
    else if (len % 3 === 1) {
        base64 = base64.substring(0, base64.length - 2) + "==";
    }
    return base64;
}
```

Which gets compiled to


```javascript
      let a = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
        A = new Uint8Array(256);
      for (let s = 0; s < a.length; s++) A[a.charCodeAt(s)] = s;
      function l(t) {
        let e = t.length,
          r = "";
        for (let i = 0; i < e; i += 3) {
          let o = t[i + 0],
            n = t[i + 1],
            A = t[i + 2];
          a.charAt(o >>> 2),
            (r += a.charAt(((3 & o) << 4) | (n >>> 4)) + a.charAt(((15 & n) << 2) | (A >>> 6)) + a.charAt(63 & A));
        }
        return (
          e % 3 == 2
            ? (r = r.substring(0, r.length - 1) + "=")
            : e % 3 == 1 && (r = r.substring(0, r.length - 2) + "=="),
          r
        );
      }
```

Still not 100% convinced that bottom output is actually correct.. it's definitely weird how that `a.charAt(o >>> 2)` is not part of the addition.
