### ISSUE TITLE
Widget verification failed under special conditions

### ISSUE THREAD

**Issue by Gujinn** [FriendlyCaptcha/friendly-challenge#170]
Hello,
I haven't found anything on the internet so I'm opening a github issue.
I get this error on `Windows 11` with chrome and firefox browsers but not edge. I also get this error with `MacOS Ventura 13.0.1` on the firefox browser. The node version is 16.16.0 and the next version is 12.2.5.

I am currently trying to use friendly captcha on a project in next. I have used the documentation (see [doc](https://docs.friendlycaptcha.com/#/widget_api)) to integrate the widget into a component. I have created a provider that adds the component to all pages of the project in the `_app.js`.
 
When the page is loaded, the widget loads but quickly displays
```Verification failed, Failed to connect to https://api.friendlycaptcha.com/api/v1/puzzle```
When I reload the page with a simple `ctrl + r` I get the same error, however when I reload the page with `ctrl + shift + r` the widget works and displays me "I am human".

`ctrl + r` 

![Screenshot 2022-12-05 at 17-41-24 Connexion Legapass](https://user-images.githubusercontent.com/71255785/205694534-f21c0ebd-618f-4f4b-9b63-6155a244ac09.png)

`ctrl + shift + r`

![Screenshot 2022-12-05 at 17-42-41 Connexion Legapass](https://user-images.githubusercontent.com/71255785/205694572-2d050e47-ffbb-4835-b100-871dbc3065fe.png)

It seems that these are CSP errors according to the console. However, I did specify in the CSP of `next.config.js` the address `https://api.friendlycaptcha.com/`.
I am attaching the console errors to this issue.

![Console Error](https://user-images.githubusercontent.com/71255785/205697952-74a1f623-2d41-47fa-866c-9494dfad24eb.png)

**Comment by gzuidhof** [comment]
I'm going to close this for now, let me know if we can help you further or if it has been resolved since. Happy to re-open

**Comment by Gujinn** [comment]
Hi, sorry I haven't come back to give you news on this issue. It seems that the problem comes from next-pwa, if we remove it from the project, we don't have this problem anymore.
