### ISSUE TITLE
Correction of translation in French

### ISSUE THREAD

**Issue by mikejpr** [FriendlyCaptcha/friendly-challenge#172]
Please find attached a correction of the French translation.

For the following button, please check if the length fits, this would be better (but also longer)

  button_start : "Cliquez ici pour lancer la vérification",
instead of
  button_start: "Cliquez ici pour vérifier",

// French
const LANG_FR: Localization = {
  text_init: "Chargement..",

  text_ready: "Vérification Anti-Robot",
  button_start: "Cliquez ici pour vérifier",

  text_fetching: "Chargement du défi",

  text_solving: "Vérification que vous êtes un humain..",
  text_completed: "Je suis un humain",
  text_completed_sr: "Vérification automatique des spams terminée", 

  text_expired: "Vérification anti-robot expirée",
  button_restart: "Redémarrer",

  text_error: "Échec de la vérification",
  button_retry: "Recommencer",
  text_fetch_error: "Problème de connexion avec",
};

**Comment by gzuidhof** [comment]
Thank you! These improvements will be in the 0.9.10 release :) (see #174)
