### ISSUE TITLE
Handling verification error.

### ISSUE THREAD

**Issue by DalmasN** [FriendlyCaptcha/friendly-challenge#173]
Hello! 

What is the recommended approach to handling verification errors? My backend (server) makes the nessecary verification POST request and returns the response to the client. But how would one update the widget to display that an error occurd while verifying the puzzle? Im using React and have based my code from your example. I tried to set the widget´s "valid" property to "false" but the widget does not update visually. Is it possible to update the widget´s state somehow? 

Thanks in advance.

**Comment by merlinfuchs** [comment]
The widget can't be used to display verification errors. You are responsible to display them if you want to.
