### ISSUE TITLE
Problems with Captcha in Blazor

### ISSUE THREAD

**Issue by xFlowneox** [FriendlyCaptcha/friendly-challenge#175]
Captcha just disappears in .Net 6 Blazor. Could you also add examples of how friendly captcha works in Dotnet blazor? I would like to use it in Blazor Server.

**Comment by gzuidhof** [comment]
I'm going to close this.. I am not sure if this issue will ever receive the input it deserves.

In the end Blazor runs in a browser, so there must be some way to bridge Blazor to the Friendly Captcha widget - but I have no experience with it whatsoever.
