### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'dataset')

### ISSUE THREAD

**Issue by fatherJS** [FriendlyCaptcha/friendly-challenge#182]
https://github.com/FriendlyCaptcha/friendly-challenge/blob/9eac3cd5833f83023a012304f8ea42ed624432bd/src/captcha.ts#L82

Throws following console error on our page: TypeError: Cannot read properties of undefined (reading 'dataset')...

**Comment by gzuidhof** [comment]
I imagine that the `element` you passed into the constructor is `undefined`, could you make sure the `HTMLElement` that you are trying to mount to is defined?
