### ISSUE TITLE
Example of validation in php

### ISSUE THREAD

**Issue by PilarDCV** [FriendlyCaptcha/friendly-challenge#187]
Hello Friendly Captcha team,
I have consulted the documentation and there are only examples of the implementation of validation with javascript. 
I wonder if it is possible to do an integration of validation with php. 
Could you provide an example? 

Thank you!

**Comment by merlinfuchs** [comment]
You can refer to the verification in our Wordpress plugins: https://github.com/FriendlyCaptcha/friendly-captcha-wordpress/blob/main/friendly-captcha/includes/verification.php
Be aware that the wordpress specific functions won't be available in a normal PHP environment. You would probably use [curl](https://stackoverflow.com/a/5676572) instead to make the post request.
