### ISSUE TITLE
Cypress implementation

### ISSUE THREAD

**Issue by felipepastor** [FriendlyCaptcha/friendly-challenge#189]
Hi,

I'm trying to implement e2e test and bypass the captcha. I'm facing a few issues and I'd like to know if someone here already faced them or could implement in a right way.

I'm using the FriendlyCaptcha as a component, the way it's described in the documentation, I only changed a few things but the idea is the same as it's there, and I'm using it over the application, in different moments. It's working fine, my backend can check it and returning if it's ok or not.

The problem now is in the e2e tests. Bypass/intercept the request isn't happening because the api is not being triggered. This happen automatic when we render the component.

I started to take a look in library code and I found this condition, when I force the click on the button:
```
if (isHeadless()) {
  this.e.innerHTML = getErrorHTML(this.opts.solutionFieldName, this.lang, "Browser check failed, try a different browser", false, true);
  return;
}
```
And now, I don't know which part is really needed to by pass it and make it initialize and I intercept the request.

Does anyone already implemented it?
Since there's not too many content online/forums. I'd appreciate any response.

Best.

**Comment by gzuidhof** [comment]
Sorry about the long delay in answering, but generally the tip would be to not solve the captcha at all in your end-to-end tests, but instead enable the submit button with a bit of Javascript (if you are disabling it in the first place). [This docs page](https://docs.friendlycaptcha.com/#/automated_testing) should provide some ways that it is generally done.

**Comment by gzuidhof** [comment]
Closing this, feel free to re-open if something is unclear or there is something to discuss further :)
