### ISSUE TITLE
Only a single FriendlyCaptcha is displayed on a certain page

### ISSUE THREAD

**Issue by sachbearbeiter** [FriendlyCaptcha/friendly-challenge#19]
Hi,

the problem description:
"At this moment a single friendlycaptcha is displayed on a certain page. So the first captcha on the open abstracts page is visible, but not the other ones.
The reason is that the friendlycaptcha javascript assumes that there will only be a single captcha:
function findCaptchaElement() {
    var el = document.querySelector(".frc-captcha");
The querySelector() method only returns the first element that matches the specified selectors.
If a page has multiple DIV.frc-captcha, as it is on the open abstracts page, then only the first is processed by the javascript, the other DIVs remain empty and invisible."

Could you solve this please?
Thanks!

**Comment by gzuidhof** [comment]
Hi sachbearbeiter,

Thank you for this report and the other one. Could you make sure you are using the latest version of the widget? Since version 0.6.2 that function was changed to the following:

```javascript
export function findCaptchaElements() {
    const elements = document.querySelectorAll(".frc-captcha");
    if (elements.length === 0) {
        console.warn("FriendlyCaptcha: No div was found with .frc-captcha class");
    }
    return elements;
}
```

Which we then loop over:
```javascript
for (let element of elements) {
    const hElement = element as HTMLElement;
    if (hElement && !hElement.dataset["attached"]) {
        autoWidget = new WidgetInstance(hElement);
        hElement.dataset["attached"] = "1";
    }
}
```

**Comment by sachbearbeiter** [comment]
Oh - ok - sorry 
I will have a look later and i'm shure, we can close this issue ;)
Thanks!

**Comment by gzuidhof** [comment]
No problem! I will close the issue, we can re-open it if this doesn't solve the problem :)
