### ISSUE TITLE
Content-Security-Policy unsafe-inline

### ISSUE THREAD

**Issue by ferhatguenes** [FriendlyCaptcha/friendly-challenge#191]
Hello FriendlyCaptcha team

We had to use unsafe-inline in script-src for our CSP to make FriendlyCaptcha work. We would like to get rid of them. What's the recommended safest CSP to use FriendlyCaptcha? I wasn't able to find anything regarding this topic in the documentation.

Our CSP currently looks like this:
`script-src 'self' unpkg.com 'unsafe-inline'; worker-src 'self' unpkg.com blob: ; style-src 'self' 'unsafe-inline'`

Thanks for helping out!

**Comment by gzuidhof** [comment]
Hi @ferhatguenes,

The following should work in most cases, which does not include the `'unsafe-inline'` directive for `script-src` or `style-src`.
```
child-src blob:; default-src 'self' 'unsafe-inline' *.friendlycaptcha.eu *.friendlycaptcha.com; script-src 'self' unpkg.com blob:
```

Do let me know if this works for your use-case. If you don't use the unpkg CDN (but instead serve the JS file from your website), you can remove `unpkg.com`. I'll close this issue, but will re-open if you run into any trouble.
