### ISSUE TITLE
Angular usage

### ISSUE THREAD

**Issue by mehdi47** [FriendlyCaptcha/friendly-challenge#192]
Hi,

I am using friendlyCaptcha with angular and .net core.

I setup the verification api on the backend, and i'm calling it on the frontEnd component.

The problem is, i have no idea how the puzzle solves itself when integrated with the form, it always ends with "I am human", while the verification api returns: 

{
    "success": false,
    "details": "Could not parse JSON or formdata, maybe you forgot the body, or the content-type header is missing?",
    "errors": [
        "bad_request"
    ]
}

And whenever i check the usage stats on the dashboard, the siteverify property is always 0.

I really could use some help here, kinda stuck on this part !

Thank you.

**Comment by gzuidhof** [comment]
Hi @mehdi47,

Could you perhaps share a snippet of code where you call the siteverify API in your backend code?

If you are sending it as JSON, you should set the content-type header `application/json` too (to tell our servers that the message you are sending it in JSON format). It's been a while that I wrote C# code, but maybe the following [post](https://www.dofactory.com/code-examples/csharp/content-type-header) can provide some examples

**Comment by mehdi47** [comment]
Hi @gzuidhof ,

Thank you for your reply,

On the frontend side, i only send the solution as a string, 

doneCallBack(solution: any){
    const url = environment.BASE_URL;

    let httpParams = new HttpParams()
                        .append('solution', solution);
    this.http.post<CaptchaResult>(url+"api/FriendlyCaptcha/VerifyCaptchaSolution", null, {params: httpParams}).subscribe(result => {
      if(result.success){
        console.log("CAPTCHA completed succesfully, solution:", solution);
        this.onDone.next(solution);
      }
    });
  }
  
  And on the backend, this is the service that calls the siteVerify api, that i'm calling in the VerifyCaptchaSolution Http Request :

public async Task<string> VerifySolution(string solution)
        {
            try
            {
                var request = new HttpRequestMessage(HttpMethod.Post, $"{_httpClient.BaseAddress}?solution={solution}&secret={friendlyCaptchaSecret}&sitekey={friendlyCaptchaSiteKey}");
                var response = await _httpClient.SendAsync(request);

                return await response.Content.ReadAsStringAsync();
            }
            catch (HttpRequestException e)
            {
                return e.Message;
            }
        }

**Comment by mehdi47** [comment]
Even when using postman, i receive the same error response

**Comment by mehdi47** [comment]
The issue is resolved, thank you,
