### ISSUE TITLE
Subscription plans and endpoints

### ISSUE THREAD

**Issue by Illia-Linevych** [FriendlyCaptcha/friendly-challenge#193]
Hi team! I am currently involved in the development of an e-commerce platform and we wanted to allow our customers to use Friendly Captcha. Therefore, each customer will have to create a Friendly Captcha account, and the corresponding site and secret keys. My question is whether there is a way to find out what type of site key each customer has created, so we can use the correct endpoints (EU or Global) for puzzle fetching and captcha verification?

**Comment by merlinfuchs** [comment]
There is currently no intended way to do this. You could fetch `https://api.friendlycaptcha.com/api/v1/puzzle?sitekey=XXXXX` and `https://eu-api.friendlycaptcha.eu/api/v1/puzzle?sitekey=XXXXX` and see which one (or both) succeeds.
Keep in mind that this API might change at any point.

**Comment by Illia-Linevych** [comment]
Thank you for your answer! Also, I want to clarify something, can we use Global endpoints (for verification and puzzle fetching) for the site key which was created as EU?
![image](https://user-images.githubusercontent.com/50486434/234244225-34819319-9144-45af-add4-cdcdc6b321e5.png)

**Comment by merlinfuchs** [comment]
The siteveriy endpoints (both EU and Global) can be used not matter which endpoints you have enabled.

The puzzle endpoint will only work on the endpoint that you have enabled. You can also enable both endpoints tho
