### ISSUE TITLE
Angular error handling

### ISSUE THREAD

**Issue by mehdi47** [FriendlyCaptcha/friendly-challenge#194]
Hi,

I have a question as i'm still trying to understand how error handling works with friendlyCaptcha.

When i call the verification api and try to simulate a wrong solution to receive the 400 error, i think when the solving is done after that, it shouldn't tell me "I am human", and yet it does do so.

I am using the errorCallBack event to try and catch the error, but it still detects it as being solved ! 

How does error catching work in this case ? and how is it possible to cancel the captcha when an error occures and show an error message instead of "i am human" .

Thank you !

**Comment by merlinfuchs** [comment]
The verification of the captcha solutio must be done in your backend by making a request to the `siteverify` endpoint. You can then display an error to your user or deny access if the verification has failed.
The widget itself shows "I am human" as soon as it has found a solution to the cryptographic puzzle. As long as the user (or bot) has not tempered with the widget that solution will always be valid.

**Comment by mehdi47** [comment]
Hi @merlinfuchs 

Thank you for responding, i agree with what you said and i did exactly the same thing, i do the verification on my backend(.net core api) and return either a positive result or an error, but even though my api returns an error, it still displays "i am human".

what i did is that i hardcoded a fake solution and sent it to my api for verification, and it still shows " i am human ", without calling the errorCallBack function.

Thank you

**Comment by merlinfuchs** [comment]
The widget itself shows "I am human" as soon as it has found a solution to the cryptographic puzzle. It doesn't know if or when you have verified the solution and if that verfication was successful. 
You can display an error yourself if the verification failed. Generally a real user should practically never encounter a failed verification as the solutions that the widget produces should always be valid.
