### ISSUE TITLE
Set skipStyleInjection via data attribute

### ISSUE THREAD

**Issue by wimski** [FriendlyCaptcha/friendly-challenge#195]
Would it be possible to support setting the `skipStyleInjection` value via a data attribute?

**Comment by gzuidhof** [comment]
Hi Wim,

It would be possible, but perhaps the following workaround will do the job: The widget will only inject its styles if no HTML element with `id` `"frc-style"` is present. You could add a dummy HTML element with such an ID:

```html
<div id="frc-style"></div>
```

(Or you could give the captcha element that ID, it doesn't really matter as long as it is present somewhere on the page.)

Would this workaround do the job for your usecase?

**Comment by wimski** [comment]
Yes, that works. Although it feels kind of _hacky_ :grimacing:
