### ISSUE TITLE
Friendly Captcha testing

### ISSUE THREAD

**Issue by Illia-Linevych** [FriendlyCaptcha/friendly-challenge#198]
Hi team! Currently, we writing web tests (using Selenium and ChromeDriver on C#) for our forms with Friendly Captcha. Unfortunately, each test fails on the verification button click and captcha shows message "Browser check failed, try a different browser":
![image](https://user-images.githubusercontent.com/50486434/236206017-176cdc16-60ad-4c21-890a-2f4e6a66892b.png)
Is there any way how we can fix that?

**Comment by sschueller** [comment]
There is a section in the documentation regarding this: https://docs.friendlycaptcha.com/#/automated_testing
