### ISSUE TITLE
Defer recommendation leads to problems

### ISSUE THREAD

**Issue by sachbearbeiter** [FriendlyCaptcha/friendly-challenge#20]
The installation page of the docs.friendlycaptcha.com says:
"It is recommended that you include the async and defer attributes like in the examples above, they make sure that the browser does not wait to load these scripts to show your website."

Regarding the defer attribute please read this page:
https://hacks.mozilla.org/2009/06/defer/
Or just quickly see this answer:
https://stackoverflow.com/questions/8638551/script-defer-and-document-ready/8638597#8638597
that says this:
"Defer is another such inconsistency that should be avoided for well written pages."

It turned out that following your defer recommendation caused difficult-to-find problems on our website, because at the time the friendlycaptcha script was executed by the browser, the .frc-captcha div did not exist yet, despite the defer attribute. So indeed, the defer cannot be relied upon.

Here is something simple that worked in our case, adding the following lines to the end of widget.js, basically wrapping the last few lines into this:

document.addEventListener("DOMContentLoaded", (event) => {
var fc = window.friendlyChallenge;
// and a few more lines...

});

It is better if you use this (or similar) method in the next version of your script, and remove the defer recommendation from the documentation.
You can also see "What is the ultimate way of detecting if document is ready in JavaScript?" at the end of this page:
https://codetonics.com/javascript/detect-document-ready/

Thanks and best wishes!

**Comment by gzuidhof** [comment]
Thank you, let me get back to you on this one. I am sorry this caused issues on your website.

My own approach is usually to include these scripts at the bottom of the page. I have had issues in the past with `DOMContentLoaded` as it is possible that the script wasn't loaded at the time this event would fire.

I think the blogpost you linked at the end has the approach we should take (check if the document is already loaded, and otherwise wait for its event).

**Comment by amenk** [comment]
What is the plan on this? Extend https://docs.friendlycaptcha.com/#/installation to recommend that it should be put before `</body>` ?

**Comment by gzuidhof** [comment]
I am not 100% sure, but I think it's best practice to put `defer`ed scripts in the `<head>`. If you put it without any defer or async tag it will slow down your page load a bit as it will wait for the script to be downloaded and parsed before showing the page at all.

Right now the "main" script looks like this:
```typescript
import { findCaptchaElements } from "./dom";
import { WidgetInstance } from "./captcha";

const fc = window.friendlyChallenge;
let autoWidget = fc ? fc.autoWidget : null;

const elements = findCaptchaElements();
for (var index = 0; index < elements.length; index++) {
    const hElement = elements[index] as HTMLElement;
    if (hElement && !hElement.dataset["attached"]) {
        autoWidget = new WidgetInstance(hElement);
        hElement.dataset["attached"] = "1";
    }
}

window.friendlyChallenge = {
    WidgetInstance,
    autoWidget
};
```

This could be changed to something like:

```typescript

import { findCaptchaElements } from "./dom";
import { WidgetInstance } from "./captcha";

function setup() {
  const fc = window.friendlyChallenge;
  let autoWidget = fc ? fc.autoWidget : null;
  
  const elements = findCaptchaElements();
  for (var index = 0; index < elements.length; index++) {
      const hElement = elements[index] as HTMLElement;
      if (hElement && !hElement.dataset["attached"]) {
          autoWidget = new WidgetInstance(hElement);
          hElement.dataset["attached"] = "1";
      }
  }
  
  window.friendlyChallenge = {
      WidgetInstance,
      autoWidget
  };
}

if(document.readyState !== "loading") {
  setup();
else {
  document.addEventListener("DOMContentLoaded", setup);
}
```

With this, regardless of `defer` it should execute only ever after the DOM's content was loaded. I haven't pushed this change yet.

The issues mentioned in the stackoverflow post are only for _really_ old browsers (IE9, Safari 4 and Mozilla 3.5). These browsers are really old (>10 years) and I doubt that FriendlyCaptcha will work in them anyway. So I'm still a bit puzzled why it was leading to issues.

Anyway the fix above should do the job, I have yet to test it in very old browsers to be sure this change won't break any of them before I can publish a new version.

**Comment by gzuidhof** [comment]
I have pushed version 0.8.5 which includes a variation of the above script. With that change it shouldn't matter whether you end up using async or defer, or where you put it in your page. Let me know if this didn't fix it for you.
