### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by papastepano** [FriendlyCaptcha/friendly-challenge#201]
The missing example for Angular.

**Comment by papastepano** [comment]
`
  @ViewChild('frccaptcha', { static: false }) 
  friendlyCaptcha: ElementRef<HTMLElement>; 

...

    const widget = new WidgetInstance(this.friendlyCaptcha.nativeElement, {
      doneCallback: (a) => {
        this.myForm.get('captcha')?.patchValue(true)
        console.log('DONE: ', a);
      },
      errorCallback: (b) => {
        console.log('FAILED', b);
      },
    })

    widget.start()
`

**Comment by gzuidhof** [comment]
Closed with #202, thank you again for the contribution :)
