### ISSUE TITLE
CAPTCHA In China

### ISSUE THREAD

**Issue by PilarDCV** [FriendlyCaptcha/friendly-challenge#208]
Hello Friendly Captcha team,

Is it possible to use friendly captcha on a Chinese server?

Thank you!

**Comment by gzuidhof** [comment]
Hi @PilarDCV,

Let me ping @dev-love, I think they know best :)

**Comment by dev-love** [comment]
Hi @PilarDCV!

Friendly Captcha should be securely accessible to Chinese users via our EU endpoint. You are welcome to test this yourself in a free 30-day trial period by creating an account with Advanced Plan or higher here: https://friendlycaptcha.com/signup/
