### ISSUE TITLE
Failing Tests With Friendly-Challenge because of:  SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by mawy1** [FriendlyCaptcha/friendly-challenge#210]
Hello together, 
So I was implementing the friendly challenge and everything works just fine. The only problem I have is, that my jest tests are now all failing because of:

`    export { WidgetInstance, localizations };
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      2 | import { FormControl, FormGroup, ValidationErrors } from '@angular/forms';
      3 | import { Observable, Subject } from 'rxjs';
    > 4 | import { WidgetInstance } from 'friendly-challenge';
        | ^
      5 |
      6 | @Component({
      7 |   selector: 'captcha',

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1495:14)`

I have already in my jest.config.js: 
`  transform: {
    '^.+\\.(ts|mjs|js|html)$': 'jest-preset-angular',
  },
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)'],`

and my preset:
`module.exports = {
  ...nxPreset,
  resolver: '@nrwl/jest/plugins/resolver',
  testEnvironment: 'jsdom',
  testRunner: 'jasmine2',
  globals: {
    'ts-jest': {
      isolatedModules: true,
    },
  },
};`. I already tried the transformIgnoreOptions but these dont help. DDo you guys know a solution?

**Comment by gzuidhof** [comment]
Sorry about the long time to response, I imagine you will want to update the regular expression in `transformIgnorePatterns` to also ignore the Friendly Captcha script you are importing. The script is in ES Module format, which sometimes Node and testing tools don't understand. We do have the `module` set in our `package.json`, which usually means it works out of the box - perhaps if you update your tools (especially Jest) it will start working without any further changes.

**Comment by mawy1** [comment]
@gzuidhof Sorry for the late reply, it helped thanks!
