### ISSUE TITLE
Changing the French translation

### ISSUE THREAD

**Issue by leofri3** [FriendlyCaptcha/friendly-challenge#211]
The French translation is not a natural statement. 

Proposed new translation (in bold): 
"text_init: "Chargement...", text_ready: "Vérification Anti-Robot",button_start: "Cliquez ici pour vérifier", text_fetching: "Chargement du défi", **text_solving**: "Nous vérifions que vous n'êtes pas un robot...",**text_completed**: "Je ne suis pas un robot",text_completed_sr: "Vérification automatique des spams terminée", text_expired: "Vérification anti-robot expirée",button_restart: "Redémarrer", text_error: "Échec de la vérification",button_retry: "Recommencer",text_fetch_error: "Problème de connexion avec"

**Comment by DoTq52** [comment]
I would appreciate it if someone can pick this up and adjust the French translation as requested above. It's a small change of text but it can be quite impactful in the end if it's not done.
Thanks for checking!

**Comment by gzuidhof** [comment]
These improvements are now in the master branch, they will be included in the new release :)
