### ISSUE TITLE
Public API to detect when puzzle verification expires

### ISSUE THREAD

**Issue by mbehzad** [FriendlyCaptcha/friendly-challenge#214]
Hi,
after a solved puzzle has expired (after ~1 hour), there seems to be no public API to be notified or detect it. I assume `widget.valid && !widget.hasBeenStarted` would work but that doesn't seem be the official way to do it.

What is the correct way to approach this?
Best
Mehran

**Comment by gzuidhof** [comment]
Hi Mehran,

You're right that there is no way to listen to that event in a straightforward way. In most cases you won't need to handle it as the user will see the widget with text that prompts them to retry: but if you'd like to disable the submit button I understand that is not sufficient.

Some approaches that come to mind:
* The hidden form field value (`frc-captcha-solution`) gets set to `.EXPIRED`. Which means you could do something like the following:  
  ```javascript
  document.querySelector("input[name='frc-captcha-solution'").value 
  ```
  With this approach I imagine you can also add an `input` event listener on that element to be notified its changes.
* Monkeypatching `widget.expire` (but that's quite hacky)
  ```javascript
   const originalFunc = widget.expire
   widget.expire = () => {
     originalFun();
      console.log("Widget has expired");
     }
  ```

In version two of the widget (not released publicly yet) there will be an `expire` event to subscribe to.. But in this version I agree it's hardly ideal. Does either of the two approaches above work for your usecase?

**Comment by mbehzad** [comment]
Hi Guido, thanx for your response.
I think the widget currently re-renders its markup so there won't be any input events. But reading the value is something that we can use.
Is it fair to assume these values `.EXPIRED` , `.UNFINISHED` , ... wont be changed in minor releases?
overriding `widget.expire` would provide exactly what i need. But i feel like it is too much based on implementation details and also Typescript isn't happy with using the private methods, so i think we will stick with checking the input value right before form submit (it is really an edge case when someone needs so long to fill-in and send the form). And looking forward for the next version. 

cheers

p.s. you can close this issue if you want

**Comment by gzuidhof** [comment]
Yes you can assume that these values will not change without a major release (which we are not planning) :)

**Comment by akz3us** [comment]
Hi @gzuidhof If puzzle solution is expired in the frontend then, the frontend sets `.EXPIRED` value  to `frc-captcha-solution`. In this case, what is the response from the friendly captcha API?

- solution_invalid
- solution_timeout_or_duplicate
If the response is  solution_invalid what would trigger solution_timeout_or_duplicate API response?

Could you please clarify this?

**Comment by gzuidhof** [comment]
Hi @akz3us, this would be `solution_invalid`. The other `solution_timeout_or_duplicate` would be triggered when one submits a solution that is otherwise valid, but either has already been used, or is past the expiry date. The reason there is the `_or_` in the name, is because we only remember solutions for so long: it could be both a duplicate *and* a timeout, or either.

The second case is possible if a user/attacker takes the value from the form, waits a long time, and then submits it - or if the logic in the page does that.

I hope that helps - in general you shouldn't need to worry about it too much unless you see a large spike of either.

**Comment by mbehzad** [comment]
I guess in Friendly Captcha V2, the [frc:widget.expire](https://developer.friendlycaptcha.com/docs/v2/sdk/events#frcwidgetexpire) event is meant to support this use case and notify the host of the expiration.
