### ISSUE TITLE
Make the restart button visible

### ISSUE THREAD

**Issue by ghenadiibatalski** [FriendlyCaptcha/friendly-challenge#22]
Hello, could you please make the restart button visible/available if the solution already exists? For the case one need to restart captcha manually.

Regards, Gena

**Comment by gzuidhof** [comment]
Hi Gena,

The widget has no way of knowing that the solution has been used (and that the restart button should be visible).

There's no one size fits all solution that I can add to the widget library, it really depends on how you use the captcha: Some people may refresh the page on submit (e.g. if you're using HTML forms without any other Javascript framework), others may send the solution to their server using AJAX or fetch (common with SPA websites). Others may not use the widget in a form at all.

Upon submitting users can also first validate the other fields and exit early, so it is possible the captcha's solution is still OK to be used again.

**Comment by ghenadiibatalski** [comment]
Hi @gzuidhof, the only purpose is to display a restart button within the widget (consistently styled) if any solution exists. If somebody wants to click it again, its okay for me. It could also be disabled by default.
