### ISSUE TITLE
Adjusting the french translation

### ISSUE THREAD

**Issue by DoTq52** [FriendlyCaptcha/friendly-challenge#222]
Hey,
Would it be possible to correct the French version of translation for **"button_start"** from "Cliquez ici pour vérifier" to **"Clique ici pour vérifier"**.

Thanks for changing in advance!

**Comment by DoTq52** [comment]
Hey @gzuidhof,
Any chance of updating this text in the French translation?

Thanks a lot for checking!

**Comment by gzuidhof** [comment]
Sure, I created this PR to address it which I will merge into master https://github.com/FriendlyCaptcha/friendly-challenge/pull/228.

It will be in the next release :)

Thank you!
