### ISSUE TITLE
How to use friendly-challenge in React Native? Is it possible?

### ISSUE THREAD

**Issue by dokselblackbit** [FriendlyCaptcha/friendly-challenge#229]

**Comment by gzuidhof** [comment]
Hi @dokselblackbit,

I don't think we have an example of using friendly-challenge in React Native. It would be similar to the way you integrate using Flutter: you would create a WebView in which the user completes the challenge - this will require writing some code on your side.

Here is a link to the Flutter example: [link](https://docs.friendlycaptcha.com/#/flutter).

**Comment by dokselblackbit** [comment]
I find a solution.
`
export const renderCaptcha = (captcha: {[key: string]: string}) => `
    <script
        type="module"
        src="https://cdn.jsdelivr.net/npm/friendly-challenge@0.9.13/widget.module.min.js"
        async
        defer
    ></script>

    <script nomodule src="https://cdn.jsdelivr.net/npm/friendly-challenge@0.9.13/widget.min.js" async defer></script>

    <script>
        function myCallback(solution) {
            window.ReactNativeWebView.postMessage(solution);
        }
    </script>

    <div
        class="frc-captcha" 
        data-sitekey="${captcha['data-sitekey']}"
        data-solution-field-name="${captcha['data-solution-field-name']}"
        data-puzzle-endpoint="${captcha['data-puzzle-endpoint']}"
        data-callback="myCallback"
        data-start="auto"
    ></div>
`;

<WebView
        source={{html: friendlyCaptcha}}
        onMessage={(event) => handleWebViewMessage(event)}
   />`
