### ISSUE TITLE
Angular data-lang rendered to lang and doesn't work

### ISSUE THREAD

**Issue by ghenadiibatalski** [FriendlyCaptcha/friendly-challenge#23]
Hello and thank you for the i18n feature

In angular the `data-lang` seems to be translated to `lang` and doesn't have any effect. The configuration via widget looks good. Could you please check the problem and eventually support both: data-lang and lang, if the problem is reproducible?

Angular
`<div #captcha class="frc-captcha" data-sitekey="xyz" data-lang="de"></div>`

Resulting HTML
`<div _ngcontent-mpr-c69="" data-sitekey="xyz" class="frc-captcha" lang="de">`

Regards, Gena

**Comment by gzuidhof** [comment]
Hi Gena,

[`data-` attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) are a standardized HTML feature, supporting other attributes may lead to weird behavior in old browsers.

I did some Googling (I'm not an Angular expert by any means), but it looks like you can set one with
```html
<div [attr.data-lang]="de"></div>
```
[Reference link where I got this from](https://lishman.io/accessing-data-attributes-in-angular)

Let me know if this works for you, I can add a tip in the docs for future Angular devs

**Comment by ghenadiibatalski** [comment]
Thank you, it works! Was my mistake.
