### ISSUE TITLE
Support for more language in data-lang attribute

### ISSUE THREAD

**Issue by samlaukinoon** [FriendlyCaptcha/friendly-challenge#230]
Today data-lang attribute support a good list of languages, however this be expanded to cover the following languages as well? This is cover more audience from MENA and APEC region.

ar (language code in ISO2) - Arabic
bs - Spanish
id - Indoneshian
he - Hebrew
fa - Persian
ko - Korean
mk - Macedonian
th - Thai
tr - Turkish

Thanks in advance!

**Comment by merlinfuchs** [comment]
Hey, right now we depend on contributors and native speakers to add support for more languages. We are open for contributions!

Spanish (ES) and Turkish (TR) are already available!

**Comment by samlaukinoon** [comment]
Thanks Merlin for the swift response.
For now are you able to include the language support for Thailand (TH) with the following details (fields under localization.ts).

text_init: "การเริ่มต้น..."
text_ready: " การตรวจสอบต่อต้านหุ่นยนต์"
button_start: "คลิกเพื่อเริ่มการตรวจสอบ"
text_fetching: "การดึงความท้าทาย"
text_solving: "ยืนยันว่าคุณเป็นมนุษย์..."
text_completed: "ฉันเป็นมนุษย์"
text_completed_sr: "การตรวจสอบสแปมอัตโนมัติเสร็จสมบูรณ์"
text_expired: "การตรวจสอบ ต่อต้านหุ่นยนต์ หมดอายุ"
button_restart: "รีสตาร์ท"
text_error: "การยืนยันล้มเหลว"
button_retry: "ลองใหม่"
text_fetch_error: "ไม่สามารถเชื่อมต่อได้"

Thanks for the great support and glad to be part of Enterprise subscription!

**Comment by gzuidhof** [comment]
Ah thank you @samlaukinoon, I have added Thai to the PR here #234, it will be in version `0.9.14` (which will be released after it's reviewed, I imagine early next week).
