### ISSUE TITLE
Hebrew translations

### ISSUE THREAD

**Issue by tinytim84** [FriendlyCaptcha/friendly-challenge#232]
We'd like to use FriendlyCaptcha on our Hebrew translated site, and we're happy to provide the translations, but before we get them I wanted to ask whether FriendlyCaptcha supports RTL languages?

**Comment by gzuidhof** [comment]
Hi Tim,

That would be great. The widget should work fine in RTL mode. If necessary you can add custom CSS rules, but by trying it myself it seems to work fine with the following:

```css
.frcaptcha {
  direction: rtl;
}
```

That makes me hopeful that no further changes would be required.

If we find that some changes are required, I'd be happy to help and we can incorporate them in this library.

**Comment by tinytim84** [comment]
Great, thank you.  I'll get on the translations and provide them here.

**Comment by tinytim84** [comment]
@gzuidhof I have the translations in an excel file.  If I paste them here it doesn't strictly keep the RTL nature of the text.  What do you suggest for me getting them to you?  Can I email them to an address?

**Comment by gzuidhof** [comment]
You could try to create a gist (https://gist.github.com) and share that. If that doesn't work, you can e-mail them to me (`<firstname>@friendlycaptcha.com`)

Thank you!

**Comment by tinytim84** [comment]
That still flipped some of the bits.  I've emailed the excel file to you.  Please let me know when the translations are in.

**Comment by gzuidhof** [comment]
I created a PR here :) https://github.com/FriendlyCaptcha/friendly-challenge/issues/232

**Comment by gzuidhof** [comment]
It's now live in `0.9.14` :)
