### ISSUE TITLE
Node 21 serverside: side-effect when importing from friendly-challenge crashes app.

### ISSUE THREAD

**Issue by WavyWalk** [FriendlyCaptcha/friendly-challenge#237]
Following problem:

With node 21 a navigator is implemented in node environment https://nodejs.org/de/blog/announcements/v21-release-announce#navigator-object-integration

We have a nextjs app.

When running in a dev mode (without treeshaking), side effect code that runs in friendly-challenge whenever it is imported crashes app, because `navigator.userAgent` is undefined.

this is the culprit:
https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/headless.ts#L4C1-L7C2

Suggest doing a null or string check there `typeof navigator !== "undefined" && typeof navigator.userAgent === 'string'`.

**Comment by merlinfuchs** [comment]
Thanks for the report and the proposed solution! I have opened a PR which should be included in the next release: #238

**Comment by Uzlopak** [comment]
In node 21.1.0 navigator has now userAgent. Is your issue now solved?
