### ISSUE TITLE
No access to autoWidget despite loading the scripts

### ISSUE THREAD

**Issue by 92ahmed92** [FriendlyCaptcha/friendly-challenge#242]
I have a single page application and I am installing friendlyCaptcha into my TypeScript/C#-project.
Using [2. Adding the widget](https://docs.friendlycaptcha.com/#/installation?id=_2-adding-the-widget)
and [Option A: Using a script tag](https://docs.friendlycaptcha.com/#/installation?id=option-a-using-a-script-tag)
the widget is being displayed but I have no access to the friendlyChallenge.autoWidget. I need the access to be able to reset the widget when the form submitted is wrong.

**Comment by 92ahmed92** [comment]
After using just https://cdn.jsdelivr.net/npm/friendly-challenge@0.9.14/widget.min.js it worked.
PS: it is not documented that one has to use just one script :/

**Comment by merlinfuchs** [comment]
I'm guessing you might forgot to set the `type="module"` and `nomodule` on the other javascript files resüectively. See https://docs.friendlycaptcha.com/#/installation
