### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by 92ahmed92** [FriendlyCaptcha/friendly-challenge#243]
Hi, 
I am happy to provide the Arabic translations of FriendlyCaptcha. How should I do this? Email it to you or add it in a PR? 
Please note that it is a RTL language.
Bests

**Comment by merlinfuchs** [comment]
Hey, really happy that you want to provide Arabic translations. Just open a PR with the new language, you can set the `rtl` flag just like Hebrew and Thai to make it RTL.

**Comment by 92ahmed92** [comment]
Arabic translation already exists in the localization.ts
