### ISSUE TITLE
How to know in the callback if verification failed

### ISSUE THREAD

**Issue by jhennebique** [FriendlyCaptcha/friendly-challenge#245]
Hi 

I'm integrating friendly by using the data callback attribute (on the widget)
How can I know in the callback function if verification has failed, for example if a bot try to fill the form ? 
Does the solution is not provided to the callback function in this case ?

**Comment by gzuidhof** [comment]
Hi @jhennebique,

The verification happens on the server. In general you can't trust the browser and the code that runs inside of it: a spammer/attacker could change the code to disable any checks. 

Usually you would put the widget inside of a form, and after submission you would verify the captcha challenge, and in case it is invalid you reject the form contents.
