### ISSUE TITLE
React example: sitekey visible and usable by anyone

### ISSUE THREAD

**Issue by DiegoMcDipster** [FriendlyCaptcha/friendly-challenge#246]
Hi,

I was able to implement FriendlyCaptcha on my website using the instructions on https://docs.friendlycaptcha.com/#/widget_api?id=full-example-in-react-with-react-hooks

It works great!  

However, my sitekey is visible to anyone inspecting my webpage. I was able to use my sitekey on another app I created.  Note,  I do not need to create an api key to make it work.  On the Friendly Captcha dashboard I have a single app that uses that site key.

Am I missing some crucial knowledge here that does in fact make it secure?

**Comment by merlinfuchs** [comment]
Hey, 
the sitekey has to be part of you frontend and is therefore not a secret value. It's not a problem if other people have access to your sitekey. 
To actually verify that a user has passed the captcha you need to call the [verification endpoint](https://docs.friendlycaptcha.com/#/verification_api) with your api key. The api key is secret and should only be used on the backend.

**Comment by DiegoMcDipster** [comment]
@merlinfuchs Thanks for the prompt response.

Currently I have a disabled submit button until I have a solution.  If I have a solution, I enable it.

But, if i understood correctly, it's a two step process before I enable the button:
1. The sitekey is used by the frontend to generate the solution
2. The solution is posted to the endpoint to verfiy that the user has passed

If the response success is returned.  Then I should enable the button.

Is that correct?

**Comment by merlinfuchs** [comment]
Yes, that would be correct. Keep in mind that the request to our verification endpoint must come from your backend. So your frontend would submit the puzzle solution to your backend, and your backend makes the request to our endpoint.

I hope that helps!

**Comment by DiegoMcDipster** [comment]
Yes, it did.  I'm using nextjs server actions, so that's what is making the api call... and so the api key is secure.

It worked!  Thanks.
