### ISSUE TITLE
Widget not rendered because of CSP

### ISSUE THREAD

**Issue by vaneatka** [FriendlyCaptcha/friendly-challenge#247]
Script is added using the nonce approach
`<script type="module" src="/scripts/widget.module.min.js" async="" defer="" nonce=""></script>`
it is rendered with Initializing message
![image](https://github.com/FriendlyCaptcha/friendly-challenge/assets/37835435/85e97bf5-d8cb-4f99-9866-5bafabe3ea5f)
and fails
![image](https://github.com/FriendlyCaptcha/friendly-challenge/assets/37835435/b4a78d13-24d0-455a-9bb0-a8a6924e9af3)

here is the failing code
` this.opts.skipStyleInjection || function() {
            if (!document.querySelector("#frc-style")) {
                const t = document.createElement("style");
                t.id = "frc-style",
                t.innerHTML = ".frc-captcha *{margin:0;padding:0;border:0;text..........",
                document.head.appendChild(t)
            }`

can you please advice anything?

**Comment by merlinfuchs** [comment]
Friendly Captcha does currently not work with the CSP directive `require-trusted-types-for` as it does not use the TrustedHTML API to inject HTML into the DOM. The TrustedTypes API doesn't have good browser support anyway

To make Friendly Captcha work you need to remoe the `require-trusted-types-for` directive from your CSP policy or if possible add an exception for the Friendly Captcha scripts.
