### ISSUE TITLE
"False negative" verification API results

### ISSUE THREAD

**Issue by ajesina** [FriendlyCaptcha/friendly-challenge#248]
I just started integrating FC into our website, and it seems like the API returns lots of "false-negative" results for verification. I reload the widget after each verification failure, but even then (also when using page reload instead of widget reload), I often get 10 failures in a row before the API returns the expected successful result.

I've tried just straight clicking on the widget each time as well as scrolling around on the website, filling in the related form, deleting previous inputs etc, adblock / no adblock, Chrome / Firefox / Edge, but my behavior doesn't seem to affect the amount of negative verification results.

Does "developer behavior" (reloading often, directly going to the form etc) affect these results? Meaning can I assume normal users will not have these issues? Sometimes the first request succeeds right away, but that seems to be the exception.

Another interesting sidenote is that none of these failed API requests show up in the Usage Stats overview, only successful requests seem to be counted.

**Comment by ajesina** [comment]
Hi,

the API response is:
```
success=false, details=puzzle solutions invalid, errors=[solution_invalid]
```

There are no network errors on the website; you can check the implementation on https://temp.verbavoice.de (scroll to the bottom). The website is WIP but should be sufficient for reproduction. Validation is done by a backend service that also serves the Javascript.

One thing that I realized could potentially cause issues is that I modified the JS to no longer add inline style, moving the style into its own file instead. It doesn't seem to affect the functionality of the widget, but I thought I'd mention it to be sure.

**Comment by gzuidhof** [comment]
Ah, this is likely the result of something going wrong from the form
through to your server making the request.

The solutions are base64 encoded, perhaps your webserver is stripping the
`/` or + character. Not every solution will have that character, which
explains the flakiness.

**Comment by ajesina** [comment]
Ah yes, you are 100% correct.

For future reference: I had to make sure to URLencode the solution twice, once going from the frontend to the backend, and then when POSTing to the API.

Still kind of interesting that those failed calls don't count towards the statistics, but not actually an issue of course.

Thanks for the very quick help.
