### ISSUE TITLE
Bypass Friendly Captcha for Automated Testing

### ISSUE THREAD

**Issue by ercegg** [FriendlyCaptcha/friendly-challenge#252]
Hi,
how can i bypass Friendly Captcha for Automated Testing in Magento 2?

**Comment by merlinfuchs** [comment]
Hey, this is the repository for [Friendly Captcha](https://friendlycaptcha.com. We sadly can't you with issues regarding reCAPTCHA.

**Comment by gzuidhof** [comment]
No worries :) 

[This page in our documentation](https://docs.friendlycaptcha.com/#/automated_testing) should hopefully explain how to test pages that are protected by Friendly Captcha. I'm not a Magento expert by any means - if you are using the plugin there, perhaps it's possible to disable the plugin for certain requesters?

I hope this helps.
