### ISSUE TITLE
Small issue with verification and extra characters (/v1/siteverify)

### ISSUE THREAD

**Issue by andreasnuesslein** [FriendlyCaptcha/friendly-challenge#255]
Hi all, 

first of: I know this is probably the wrong place since this here is about the client; however I didn't see a good channel on the website and the normal "contact form" usually does not reach a dev. unlike here :)

So: I was trying to force an invalid solution to see what I would get back to show it to the frontend, so I did this:

```diff
    friendly_captcha = requests.post(
        "https://api.friendlycaptcha.com/api/v1/siteverify",
        data={
-           "solution": dat["frc_solution"],
+           "solution": dat["frc_solution"] + "X",
            "secret": settings.FRIENDLYCAPTCHA_SECRET,
            "sitekey": settings.FRIENDLYCAPTCHA_SITEKEY,
        },
    ).json()
```

however I still got  a `success` response.

Only when appending instead of prepending, i triggered an `solution_invalid` or something like that.:

```diff
    friendly_captcha = requests.post(
        "https://api.friendlycaptcha.com/api/v1/siteverify",
        data={
-           "solution": dat["frc_solution"],
+           "solution": "X" + dat["frc_solution"],
            "secret": settings.FRIENDLYCAPTCHA_SECRET,
            "sitekey": settings.FRIENDLYCAPTCHA_SITEKEY,
        },
    ).json()
```

I know this is probably not a major issue, but I figured I'd report it anyways. Other people might stumble over this problem too and be confused as well

**Comment by gzuidhof** [comment]
Hey, the solution encodes a bunch of different things in different sections - the last section is only used for diagnostics and isn't critical: it tells things like which solver was used (e.g. the fast WASM solver, or a fallback JS solver used in ancient browsers).

The first bit is a signature to make sure the puzzle isn't tampered with, so that is rather critical.

I hope that makes sense :)

**Comment by andreasnuesslein** [comment]
ah super, yes thanks. I had a feeling it wasn't critical but I wanted to inform you guys anyways :+1: 
cheers
