### ISSUE TITLE
OpenAPI path returns 404

### ISSUE THREAD

**Issue by airammateos** [FriendlyCaptcha/friendly-challenge#259]
Hello,

I have created an account for later integration into a high traffic project. I'm trying to call the endpoint "/api/v1/authInfo" as stated in the documentation in this URL (https://docs.friendlycaptcha.com/openapiv3.json) and it always returns a 404. Are there any account limitations by its type? 

I can use the rest of the endpoints ("puzzle" and "siteverify") without any problem.

Regards
![2024_05_21_16_41_14_authinfo_cabildo_tf_frontal_sede_electronica_Visual_Studio_Code](https://github.com/FriendlyCaptcha/friendly-challenge/assets/1295906/ae406277-6eee-4d6d-bea8-41f31a9acc47)

**Comment by gzuidhof** [comment]
Ah I apologize for the confusion, this endpoint is currently only available on the EU endpoint. If you change the URL to `eu-api.friendlycaptcha.eu` that should work. 

We're looking into shipping more "meta" endpoints for customers to manage their accounts and probably an endpoint to check the validity of an API key would be a part of that. I don't think we'll ship that in the next 3 months though - so for now the answer would be to use the EU endpoint.

**Comment by airammateos** [comment]
Hi,
Thanks for answering. With your clear answer that 404 makes sense ;-)
The idea is to contract a plan but, during development, we will skip this step to advance it.

Thanks and regards.
