### ISSUE TITLE
IE 11 fails to show any FriendlyCaptcha UI

### ISSUE THREAD

**Issue by Sevyls** [FriendlyCaptcha/friendly-challenge#26]
IE 11 fails to load FriendlyCaptcha with provided minified widget javascript at all.

Dev Tools Console shows an Exception, but no clue how to fix that. It happens with and without polyfills.  

You refer to support IE11 out of the box - this is not working for us.
https://docs.friendlycaptcha.com/#/browser_support?id=internet-explorer

![Bildschirmfoto 2021-03-12 um 16 24 39](https://user-images.githubusercontent.com/547842/110960859-7c89e900-834f-11eb-9225-f714d037af2a.png)

**Comment by Sevyls** [comment]
Find attached the position where the exception occured in the minified version

![Bildschirmfoto 2021-03-12 um 16 26 46](https://user-images.githubusercontent.com/547842/110961212-d2f72780-834f-11eb-8ac6-6a070ccdc5b5.png)

**Comment by Sevyls** [comment]
![Bildschirmfoto 2021-03-12 um 16 31 07](https://user-images.githubusercontent.com/547842/110961707-60d31280-8350-11eb-829d-a33d41d6f861.png)

I think this is an issue in fetch.umd.js line 446

**Comment by gzuidhof** [comment]
Thank you for letting us know, I'll look into this.

It looks like version 0.6.1 does work (maybe 0.6.2 too, haven't tried that one), but that does not include some newer features (localization in particular), but maybe it can be a band-aid until we figure out how to work around this problem.

**Comment by Sevyls** [comment]
I do get this exception when using widget.js 0.8.1

TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");

trace:
![Bildschirmfoto 2021-03-12 um 17 01 44](https://user-images.githubusercontent.com/547842/110965598-a265bc80-8354-11eb-8d99-f324cb2565ed.png)

**Comment by gzuidhof** [comment]
Aha, that's very useful.. I expect it's something silly like replacing 

```
for (let element of elements) {
```

in main.ts with a manually written for-loop. I currently don't have access to a Windows machine to try it.

**Comment by Sevyls** [comment]
I will see if I can fix it myself and may provide a merge request
