### ISSUE TITLE
Predefined theme based on data-theme

### ISSUE THREAD

**Issue by tn3w** [FriendlyCaptcha/friendly-challenge#261]
Is there a way to implement that the page can preset the theme of the widget with data-theme like this:
```html
<div class="frc-captcha" data-sitekey="<SITEKEY>" data-theme="<dark/light>">
```

Google reCaptcha, hCaptcha and Cloudflare Turnstile also use data-theme for this purpose.
By the way: Why is data-lang not data-language like all others on the market and why is the solution in the token `frc-captcha-solution` not `frc-captcha-response` like the competitors e.g. Google reCaptcha: `g-recaptcha-response` or hCaptcha: `h-captcha-response`?

**Comment by gzuidhof** [comment]
Hi @tn3w,

We do support theming, we use a plain CSS class for it, see the [docs here](https://docs.friendlycaptcha.com/#/theme). The tl;dr is `class="frc-captcha dark"`.

For the other changes: you're right that it's a bit different from other captcha providers. We are rolling out version two, and there it's a lot more similar (`frc-captcha-response`, `theme=dark`, and automatically doing language detection). The docs for that are found [here](https://developer.friendlycaptcha.com). If you want we can provide you with an invite to the beta preview - we don't recommend it yet for critical production usecases.

**Comment by tn3w** [comment]
OK. Thanks a lot, it seems to work now.
