### ISSUE TITLE
Progress element HTML has incorrect text

### ISSUE THREAD

**Issue by richardpenny-bp** [FriendlyCaptcha/friendly-challenge#262]
Hello, it looks like the Widget is providing an incorrect text value inside the <progress> element.

Here is an example: 

```js
<progress class="frc-progress" value="0.10416666666666667" title="5/48 (462K/s)">0.10%</progress>
```

The value of 0.1046 corresponds to a percentage of 10%, rather than 0.10%.

**Comment by gzuidhof** [comment]
Thank you :) It should be fixed in the next release

**Comment by richardpenny-bp** [comment]
Super, thank you!
