### ISSUE TITLE
Problem with two widgets on one page.

### ISSUE THREAD

**Issue by rawsta** [FriendlyCaptcha/friendly-challenge#280]
The general integration of FC into our forms is working fine.
But now we ran into an issue when there are multiple widgets on a page.

I know that I can change the `data-solution-field-name`, but are there any other methods to differentiate the two forms?
When we want to verify the first widget, we only get the second widget.

There's probably an easy solution, that I can't see right now.

**Comment by rawsta** [comment]
I found a solution by going through old issues and found a comment with a fix: 
https://github.com/FriendlyCaptcha/friendly-challenge/issues/80#issuecomment-1290048461

**Comment by gzuidhof** [comment]
Thank you for linking the workaround - this is definitely a rough edge (that is hard to fix in a backwards-compatible way).

In Friendly Captcha v2 we took this learning and improved support for multiple widgets
