### ISSUE TITLE
Focusin event not firing in Safari

### ISSUE THREAD

**Issue by gzuidhof** [FriendlyCaptcha/friendly-challenge#3]
See comment [here](https://github.com/matomo-org/matomo/issues/13905#issuecomment-661134540), the captcha widget does not automatically start solving in some browsers (Safari).

**Comment by supervisitor** [comment]
FYI: ... this picture [here](https://github.com/matomo-org/matomo/issues/13905#issuecomment-661134540) was not with Safari, this is Opera! 😳

**Comment by supervisitor** [comment]
To edit the topics at the right place: [here](https://github.com/gzuidhof/friendly-challenge/issues/4#issuecomment-661912484) is another small mistake, it is Opera on BSD, not Windows! And to define it correctly, it is version 68.0.3618.173... 😇

**Comment by gzuidhof** [comment]
I'm going to close this issue - I was not able to reproduce the issue in Opera on my MacOS machine (been a while - but just tried it again).

Developers can use the FriendlyCaptcha JS API to trigger the start of solving manually to work around issues on certain devices. They could listen to focus event on individual form elements which should most definitely fire.
