### ISSUE TITLE
Support Content Security Policy

### ISSUE THREAD

**Issue by 9mido** [FriendlyCaptcha/friendly-challenge#31]
Please provide links or directions in the docs to implement content security policy.

Examples:

https://stripe.com/docs/security/guide#content-security-policy

https://docs.hcaptcha.com/#content-security-policy-settings

**Comment by gzuidhof** [comment]
Hi 9mido,

One of the benefits of FriendlyCaptcha is that you won't need to do this! With HCaptcha or Stripe visitors on your website will make a request to  `stripe.com/script.js` or something similar. That can be problematic if stripe.com ever gets compromised (I am sure they won't, we love Stripe, but it's always a risk).

With FriendlyCaptcha you can put the JS file on `your-website.com/friendlycaptcha.js` or wherever works for you :).

**Comment by 9mido** [comment]
@gzuidhof Well, I received quite a few content security policy errors in the browser console when trying to use friendlycaptcha with https://github.com/mozilla/django-csp

Yes I know that you can store the javascript locally, but I do not wish to do that.

**Comment by gzuidhof** [comment]
The best practice would be to use a SRI hash. You can enforce these using your CSP, this will prevent any tampering. 

You can use a tool such as https://report-uri.com/home/sri_hash to calculate the SRI hash.  Your import would become something like:

```
<script src="https://unpkg.com/friendly-challenge@0.8.5/widget.min.js" integrity="sha256-BZedRoswl4WB46LGxsDSuB72tn89BAJebc4aM2wyipw= sha384-6I+7lORRqpYM0GKYMyagyjXQeqHnIAxr74eGtifnJhFwRW+ufSnJJadfc/Xf9Jpd sha512-6FokEBwNHEGC17CYg3oMder9QCbPb/7RSU3DWYXfeL0oCk6TG8aslpH9GK2/kpcqnAsknuRoMlTTEAqjWAsc+Q==" crossorigin="anonymous"></script>
```

As for the sources of the scripts: you only need to add the domain of the CDN of your choice (e.g. unpkg or jsdelivr).
