### ISSUE TITLE
Widget icons not visible

### ISSUE THREAD

**Issue by 9mido** [FriendlyCaptcha/friendly-challenge#32]
I am not seeing the black icons as shown in "Screenshots of the widget in action":

https://docs.friendlycaptcha.com/

I followed the install docs exactly. It may have to do with bootstrap CSS because the button inside the widget is 100% width.

**Comment by gzuidhof** [comment]
Have you been able to figure this out? I imagine it it some CSS issue, perhaps by overriding some styles with `!important` you can fix it. If you have an example page I can help you figure it out.

**Comment by 9mido** [comment]
No I did not. I am aware that you could use `!important` but that seems more like a hack. I will not be using friendly-captcha until you add in CSP links and perhaps lower the price.
