### ISSUE TITLE
Verification API: Response Mismatch to Documentation

### ISSUE THREAD

**Issue by fdeberle** [FriendlyCaptcha/friendly-challenge#36]
[According to the documentation](https://docs.friendlycaptcha.com/#/verification_api?id=the-verification-response), the response looks like this:

```
{
  "success": true|false,
  "errorCodes": [...] // optional
}
```

But in fact I get something like this:

```
{
  "success": false,
  "details": "puzzle expired",
  "errors": [
    "solution_timeout_or_duplicate"
  ]
}
```

Could you please clarify and update the documentation?

**Comment by gzuidhof** [comment]
Thank you for the issue.

The details message is there to help debug but it shouldn't be depended upon in your code. It would for give you a bit more of a hint if for instance you accidentally used the wrong sitekey during verification than just `"invalid_solution"`.

I'll add a note of this in the documentation for the next release

**Comment by gzuidhof** [comment]
Thinking about it a bit more, I'm hesitant to add it to the documentation. The details field should not be depended upon (i.e. one shouldn't do `if (response.details == "something") ...`, I don't want it to be part of the API contract as it is implementation dependent in what order potential errors are checked.

I'm afraid that the moment I add it to the documentation it is more likely users will start depending on it (even if there's text saying not to do so). Not sure how to proceed here, happy to hear your thoughts!

**Comment by fdeberle** [comment]
My point was more that the documentation shows a table with
Error code | Status | Description

But the response doesn't contain the status and the errorCodes differ, for instance:

documented: **timeout_or_duplicate**
received: **solution_timeout_or_duplicate**

I do not understand how to implement the mentioned [Verification Best practices](https://docs.friendlycaptcha.com/#/verification_api?id=verification-best-practices) without receiving the status code 200 itself.

**Comment by gzuidhof** [comment]
Oh I see. I'm sorry, I totally missed that, I can't believe I didn't notice this earlier 🤦. I will update the docs to reflect the true responses.

**Comment by gzuidhof** [comment]
The docs have been updated, and I just published 0.8.6 which includes the SSR improvements. Thank you for both!

**Comment by fullstackguru0711** [comment]
Hello @gzuidhof , I am running several game sites, currently got weird error involved with solution_timeout_or_duplicate

```
<script type="module" src="https://cdn.jsdelivr.net/npm/friendly-challenge@0.9.18/widget.module.min.js" async defer></script>
<script nomodule src="https://cdn.jsdelivr.net/npm/friendly-challenge@0.9.18/widget.module.min.js" async defer></script>
```

After import this script, I inserted friendlycaptcha component as documentation

`<div class="frc-captcha" data-sitekey="FC..8V" data-lang="de" data-start="auto" data-callback="getGR"></div>`

As well, I've implemented the captcha api in backend

    ```
$_captcha_solution = $input['frc-captcha-solution'] ?? '';
    $postdata = [
        'solution' => $_captcha_solution,
        'secret' => 'A1T4HOJ8CPGM4JKE0PCU6RCO27KDKLTUU227DMD560AUMFEGKIJAI795CF',
        'sitekey' => 'FCMQ9NR4HQ5P8B8V'
    ];
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api.friendlycaptcha.com/api/v1/siteverify');
    curl_setopt($ch, CURLOPT_TIMEOUT, 10);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);
    
    $response = curl_exec($ch);
    curl_close($ch);
    $resp = json_decode($response);
    if (isset($resp->errors)) {
        return jsonError('Friendlycaptcha muss zuerst verifiziert werden');
    }
```

The friendlycaptcha is working for some users when I input email, password in login form, but when I input admin user, it is not working even though the postdata that sent to 'api.friendlycaptcha.com/api/v1/siteverify' was not changed, it's really weird for me

For instance, I've input username is 'blar', password is 'Fr3...L', after verified captcha, I sent login request, the login is working.
But, I've input admin username is 'xxlmarketingsolution' is 'Er2...L' after verified captcha, I sent login request, the login is not working, I got this error
`{ ["success"]=> bool(false) ["errors"]=> array(1) { [0]=> string(29) "solution_timeout_or_duplicate" } }`
Even though when I try to login with admin user at first loading, the same error occurs
Also, after got error with admin user, when I try with other user, it's not working, the same error is occured,
Please take a look my error, It would be helpful for me any advise
Thank you man

**Comment by gzuidhof** [comment]
Hi @fullstackguru0711,

This can be caused by your system somehow retrying the same captcha solution more than once. A captcha solution is only valid once. Maybe when the user submits the form, and something goes wrong (e.g. the e-mail they entered is invalid or the password is incorrect), the widget does not get reset?

You can call `.reset()` on the widget (or refresh the page of course).

**Comment by fullstackguru0711** [comment]
Really appreciate for your quick reply,
When I try to login with special user (admin) at first reloading, I got same error with only the admin user, but worked for other users
Actually I don't think the username, password will be affect to friendlycaptcha api, but it is now for me

**Comment by fullstackguru0711** [comment]
Hi @gzuidhof , Yes, it was totally my falut, It seems I sent request twice with same solution
Thank you for your kind answer!
