### ISSUE TITLE
verification response 403 error code: 1010

### ISSUE THREAD

**Issue by mtths** [FriendlyCaptcha/friendly-challenge#45]
when trying to verify the solution we get a plain text response with status 403 (which does not seem to be documented).

this is on an internal system (which is why the widget is called with an app with the domain left blank - appid 394675017)
unfortunately we did not save the original api-key we created, but subsequently created keys should supersede it, right?

our request looks like this

     my $ua = LWP::UserAgent->new; 
     my $req = HTTP::Request->new('POST',
         'https://api.friendlycaptcha.com/api/v1/siteverify');
     $req->header('Accept' => 'application/json');
     $req->content_type('application/json');

     $req->content(encode_json({
              solution => $solution,
              secret   => $FRC_API_KEY,
         }));
     my $res = $ua->request($req);

what are we doing wrong here?

**Comment by gzuidhof** [comment]
Hi mtths,

To be honest I'm not quite sure, I went through our code to see where a bare status response may be given but it wasn't immediately evident to me, the code you shared looks good to me, also I didn't find any new errors in our error monitoring (Sentry)..

Let's try to figure it out :)

Two pointers that can maybe help:
* Could you maybe try to make the same request with a tool like [Postman](https://www.postman.com/)? If you can reproduce it there it will be easier for me to try on my end too.
* [Here's how we make the request in the Wordpress plugin](https://github.com/FriendlyCaptcha/friendly-captcha-wordpress/blob/main/friendly-captcha/includes/verification.php#L5-L25). It looks pretty much the same as your code except for using Wordpress-specific stuff for the request 😕

**Comment by mtths** [comment]
seems to be some error how we are doing the request, because indeed via curl i get proper responses

    $ curl -H 'Accept: application/json' -H 'Content-type: application/json' -X POST \
           https://api.friendlycaptcha.com/api/v1/siteverify \
           -d "{\"solution\":\"$solution\",\"secret\":\"$secret\"}"
    {"success":true}

thanks

**Comment by mtths** [comment]
turns out the useragent was the problem, when i change it from 'libwww-perl/6.52' to something else, the requests work. maybe cloudflare is the culprit here

**Comment by gzuidhof** [comment]
I imagine it must be something weird going on with Cloudflare indeed..

Thank you for sharing the culprit, it may help somebody else in the future :).
