### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by aniolpages** [FriendlyCaptcha/friendly-challenge#49]
// Spanish
const LANG_ES: Localization = {
  text_init: "Inicializando..",

  text_ready: "Verificación Anti-Robot",
  button_start: "Haga clic para iniciar la verificación",

  text_fetching: "Cargando desafío",

  text_solving: "Verificando que eres humano..",
  text_completed: "Soy humano",

  text_expired: "Verificación Anti-Robot expirada",
  button_restart: "Reiniciar",

  text_error: "Ha fallado la verificación",
  button_retry: "Intentar de nuevo",
  text_fetch_error: "Error al conectarse a",
};

**Comment by gzuidhof** [comment]
Thank you so much @aniolpages!

I have pushed version 0.8.10 with both your Spanish and Catalan localizations 🚀🇪🇸 (no flag emoji for Catalonia 😞)
