### ISSUE TITLE
Types not available for compat build (TypeScript)

### ISSUE THREAD

**Issue by kristho91** [FriendlyCaptcha/friendly-challenge#58]
It seems that no types are available when using the compat build like this:

```import { WidgetInstance } from 'friendly-challenge/compat';```

It works beautifully when using the regular build.

**Comment by gzuidhof** [comment]
Ah - this should be an easy fix on our end, we can copy the existing `friendly-challenge.d.ts` to sit next to `compat/index.js` as `compat/index.d.ts` and the tooling should understand it. 

I'll add it to our to-do list.

**Comment by yzahad** [comment]
hey,
looks like this error is again present.

`error ts(2740): Type 'WidgetInstance' is missing the following properties from type 'HTMLDivElement': align, addEventListener, removeEventListener, accessKey,`

using npmjs package Version 0.9.15

with vercel build

**Comment by gzuidhof** [comment]
Hmm, this might be something else entirely - that's a really strange error. Are you perhaps trying to store an instance `WidgetInstance` into a variable that was defined before? Could you maybe share a snippet of code?
