### ISSUE TITLE
Compat build is the same as regular build

### ISSUE THREAD

**Issue by kristho91** [FriendlyCaptcha/friendly-challenge#59]
I've been trying to make our captcha work in IE11 - it works perfectly in Firefox, Edge and Chrome.

With both the regular build and the compat build I get this error in IE11:

```SCRIPT1014: Invalid character```

I tried to compare the outputs that webpack is giving me, when using either regular or compat build - and the output are the same. And it contains template literals in the output (which I think is the issue).

Do you have any ideas if this is a issue with your build, or my setup? :)

**Comment by gzuidhof** [comment]
Hi kristho91,

I assume you are bundling your own application as standalone I can't reproduce the issue (you can try opening [this page](https://unpkg.com/friendly-challenge@0.8.12/polyfill.html) in IE11 to see the widget work - although it's rather slow it does work).

The widget uses workers to solve the puzzles in the background (so the main thread and UI doesn't freeze), this worker code is embedded as a string in the code. That string the only difference between the compat and regular build: the rest of the code is still modern Javascript. You will have to use a tool like Babel to bring it down to a level where IE11 will understand it (ES5).
  There is a little blurb of explanation [here](https://docs.friendlycaptcha.com/#/browser_support?id=compatability-mode-for-the-library), but I can totally understand how you could miss that.
