### ISSUE TITLE
https://docs.friendlycaptcha.com/ is not friendly

### ISSUE THREAD

**Issue by KOLANICH** [FriendlyCaptcha/friendly-challenge#66]
It requires JS.

**Comment by dev-love** [comment]
If you have concrete suggestions to improve FC, feel free to add a pull request :)

**Comment by KOLANICH** [comment]
It's your claim of your project being "friendly" and "privacy-first", not mine.

**Comment by dev-love** [comment]
Yes! And that is what we stand for personally.

I’d say that JavaScript is a fairly friendly programming language and its totally fine to use JS in any modern web application.

**Comment by KOLANICH** [comment]
>JavaScript is a fairly friendly programming language

You meant your solution is privacy-friendly, didn't you? JS is not privacy and security friendly.

>and its totally fine to use JS in any modern web application.

It is not privacy- and security-friendly, so absolutely not.
