### ISSUE TITLE
Add Swedish translation

### ISSUE THREAD

**Issue by astonsson** [FriendlyCaptcha/friendly-challenge#68]
// Swedish
const LANG_SV: Localization = {
  text_init: "Laddar...",

  text_ready: "Anti-robot-verifiering",
  button_start: "Klicka för att starta verifieringen",

  text_fetching: "Hämtar utmaning",

  text_solving: "Verifierar att du är en människa...",
  text_completed: "Jag är en människa",

  text_expired: "Anti-robot-verifieringen har löpt ut",
  button_restart: "Börja om",

  text_error: "Verifieringen misslyckades",
  button_retry: "Försök igen",
  text_fetch_error: "Lyckades inte ansluta till",
};

**Comment by gzuidhof** [comment]
Thank you for this!

It took a while, but with [this commit](https://github.com/FriendlyCaptcha/friendly-challenge/commit/87282feb6f494a9dfd1fd2378f9abc097411c740) your translations will be included in the next release! 🇸🇪 🇸🇪 🇸🇪

**Comment by astonsson** [comment]
@gzuidhof That's awesome! Looking forward to implement v. 0.9.1 on our website. Thanks!
