### ISSUE TITLE
Does FriendlyCaptcha have a test mode?

### ISSUE THREAD

**Issue by matt123321123** [FriendlyCaptcha/friendly-challenge#69]
Hi,

is there a way to set FriendlyCaptcha up for test mode? I would like to write testcafe tests for some pages that are secured with FriendlyCaptcha. Recaptcha for example, has a special siteKey and secretKey that you can use so that it will always let you through.

**Comment by matt123321123** [comment]
I just wanted to raise the attention for this topic, since I do not have a solution yet. If there is anything unclear about my question, please let me know :-)

**Comment by gzuidhof** [comment]
I'm going to close this issue, but feel free to re-open if you have more questions or if something is unclear about my proposed solution

**Comment by matt123321123** [comment]
Hi Guido,
thank you for you swift reply. Mocking the API sounds like a good idea and I will try that. Thank you :-)
