### ISSUE TITLE
Docs: Unclear which specific product will enable the EU endpoint

### ISSUE THREAD

**Issue by mcguffin** [FriendlyCaptcha/friendly-challenge#74]
It should be made clear whether you need a personal, growth, advanced or enterprise plan, to enable the dedicated EU-Endpoint.

This page:
https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/docs/eu_endpoint.md

Should clearly refer to the plans on pricing page:
https://friendlycaptcha.com/#pricing

**Comment by gzuidhof** [comment]
Hi @mcguffin,

The page refers to it at the end of the intro (`Note: Using this service requires a Friendly Captcha Business or Enterprise plan.`), perhaps it's not super clear as it's in a blockquote. Would putting it in bold text instead be more clear?
