### ISSUE TITLE
Change Display Name of Account

### ISSUE THREAD

**Issue by LangAaron71** [FriendlyCaptcha/friendly-challenge#76]
Hello,

is there a chance to change the Display Name of a new created account?
I have to invite colleagues and want to change Display Name to company name.

Kind regards
Aaron

**Comment by gzuidhof** [comment]
Hi Aaron,

Soon (hopefully late this month, but definitely this quarter) we're launching a new user dashboard which will allow you to do this yourself, but for now we can do this for you manually.

Could you send an e-mail using the e-mail you signed up with to support@friendlycaptcha.com? In this e-mail could you include your account id (visible in the dashboard) in the message as well as your desired Display Name? 

Thank you! :)

**Comment by LangAaron71** [comment]
@gzuidhof Thanks for your help, sent email! 
Best regards
Aaron
