### ISSUE TITLE
Compatibility with Angular

### ISSUE THREAD

**Issue by marie230** [FriendlyCaptcha/friendly-challenge#79]
Hey FriendlyCaptcha team,
is it possible to integrate FriendlyCaptcha into an Angular application?

**Comment by gzuidhof** [comment]
Hi @marie230,

I don't see why it wouldn't be possible :), and I believe it [has been used in Angular apps before](https://github.com/FriendlyCaptcha/friendly-challenge/issues/23), but I'm afraid I don't have an example ready to go. I'm happy to leave the issue open for a week so maybe others can leave pointers.

Of course if you figure it out and have some snippets to share I'd be more than happy to add them to the docs!

**Comment by merlinfuchs** [comment]
I would guess it works very similar to the [React example](https://docs.friendlycaptcha.com/#/widget_api?id=full-example-in-react-with-react-hooks). The main difference being how you get a reference to the DOM element that you want to attach the widget to.
Maybe this will help: https://ultimatecourses.com/blog/element-refs-in-angular-templates

**Comment by merlinfuchs** [comment]
```ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import { WidgetInstance } from 'friendly-challenge';

@Component({
  selector: 'app-root',
  template: ` <div #friendlyWidget>yeet</div> `,
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements AfterViewInit {
  @ViewChild('friendlyWidget') container: ElementRef<HTMLElement>;
  widget: WidgetInstance;

  ngAfterViewInit() {
    this.widget = new WidgetInstance(this.container.nativeElement, {
      startMode: 'auto',
      sitekey: 'my-sitekey',
      doneCallback: (solution) => console.log(solution),
    });
  }
}
```
This should work, but I'm not sure if it's the best way to do it in Angular.

**Comment by derHodrig** [comment]
We will add this in near future to our angular 13 app. There is no poblem since, angular understands html and has tools for the api request. So where should be a problem? @marie230

**Comment by BenjaminVettori** [comment]
I can confirm that FriendlyCaptcha definitely works with Angular 12 and 13, using the friendly-challenge npm package.
You can just use the friendly-challenge npm package as @merlinfuchs described.
I suggest, building your own "FriendlyCaptcha" component as a wrapper and pass options as ```@Input``` and handle events (onDone, onError, ...) as ```@output```. This way you can re-use the captcha component in multiple places.

e.g.

```ts
import { AfterViewInit, Component, ElementRef, ViewChild, Input, Output, EventEmitter } from '@angular/core';
import { WidgetInstance } from 'friendly-challenge';

@Component({
  selector: 'app-friendly-captcha',
  template: ` <div #friendlyWidget class="frc-captcha"></div> `
})
export class FriendlyCaptchaComponent implements AfterViewInit {
  @ViewChild('friendlyWidget') container!: ElementRef<HTMLElement>;
  widget: WidgetInstance | undefined;

  @Output() onDone = new EventEmitter<string>();
  /* add more events here if necessary */

  @Input() startMode: "auto" | "focus" | "none" | undefined;
  @Input() siteKey: string | undefined;
  @Input() puzzleEndpoint: string | undefined;
  /* add more inputs here if necessary */


  ngAfterViewInit() {
    this.widget = new WidgetInstance(this.container.nativeElement, {
      startMode: this.startMode ?? 'auto',
      sitekey: this.siteKey,
      puzzleEndpoint: this.endPoint,      
      doneCallback: (solution) => this.onDone.next(solution),
    });
  }
}

```
