### ISSUE TITLE
Why using worker.js and not worker.compat.js for polyfilled version?

### ISSUE THREAD

**Issue by gliesche** [FriendlyCaptcha/friendly-challenge#8]
Thanks for this great library and the recent update providing a widget including polyfills. I do have one question though. To me it only makes sense to use the polyfills in browsers that also need the worker.compat.js script. Wouldn't it make more sense to use the compat worker in the polyfilled widget?

**Comment by gzuidhof** [comment]
As far as I can tell `worker.compat.js` is used in the polyfilled widget, I've tested it in a bunch of old browsers where it works (or maybe I misremember). There are so many intermediate steps and scripts though it's hard to tell so I dont' blame you :)

Here's a screenshot of a relevant section, the selected part is where the worker's script is defined (and that part of the code is a polyfill that is only present in the worker compat script).
![Screenshot of widget.polyfilled.min.js](https://i.imgur.com/pXXmjoO.png)

I usually use Firefox 35 (released to main channel January 2015) to test polyfills and compat versions, the polyfilled version works in that browser (try it here: [**HTML file**](https://unpkg.com/friendly-challenge@0.6.0/polyfill.html))

**Comment by gliesche** [comment]
Ok then there might be some scripts that I really don't understand completely. I thought due to this line:

https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/captcha.ts#L5

the worker.js and not the worker.compat.js is being used. I guess during the built steps some renaming or something takes care, that the compat version is the one being imported here...

Thanks for looking into it.

**Comment by gzuidhof** [comment]
The build tool (rollup) does a string replacement of that line, so I can
understand the confusion.. it's not the cleanest way but it works :)

**Comment by gliesche** [comment]
Thanks @gzuidhof - That explains it ;)
