### ISSUE TITLE
friendlyChallenge.autoWidget should store all widgets initialized

### ISSUE THREAD

**Issue by JPustkuchen** [FriendlyCaptcha/friendly-challenge#80]
### Problem:
We have multiple captchas on a page, some of them are initialized via AJAX.
`friendlyChallenge.autoWidget` would be helpful to retrieve the initialized widgets, but it only seems to return the latest instance?

### Proposed solution:
Add `friendlyChallenge.widgets` or `friendlyChallenge.autoWidgets` which stores all instances, not just the last to allow iterating them.

Keep `friendlyChallenge.autoWidget` as single value to be backwards compatible

**Comment by gzuidhof** [comment]
This is a good suggestion, thank you! I agree that `autoWidgets` makes sense to add, I'm happy to accept a PR for that and we can merge it for the next version. The only downside is that the memory of the widgets would no longer be garbage collected.

I imagine that most users who use any of the JS API methods use the `friendly-challenge` library on its own - but I also understand that sometimes that's not the pragmatic solution. Would it maybe be a solution for you? 

I was thinking whether there might be an alternative workaround for now, but I couldn't come up with something proper. One approach would be to delete all the HTML elements and insert new ones, but that's really hacky.

I'd like to merge a few more changes before minting a new version (especially #75, and adding the new language contributions Swedish and Russian) - so a new release may only be later this month.

**Comment by gzuidhof** [comment]
Ah I see the other issue now #81, perhaps that is the better approach as it doesn't have this memory leak issue, and is also easier to reason about (e.g. would a destroyed&disconnected widget still be in the list or not?).

**Comment by JPustkuchen** [comment]
@gzuidhof thank you very much for your feedback!

Well while I agree with your considerations, I'm not sure if deciding against the full list (with removal on destroy, ...) this should also mean to decide against the single entry friendlyChallenge.autoWidget with the latest widget.

Suggesting reopening this for general thoughts about it as I think the list would be logically correct and only saving the last one seems wrong by design?

I'm absolutely fine with every decision, just wanted to point this out.

**Comment by merlinfuchs** [comment]
> The only downside is that the memory of the widgets would no longer be garbage collected.

To remove dead widgets from a potential `autoWidgets` array we could use `widget.e.isConnected`. That should tell us if the element is part of the DOM.

**Comment by dev-love** [comment]
One possible solution: 
Just give each widget element a unique ID and then make a small javascript function which gets the element using `document.getElementById` (as suggested in my previous response) and then returns the `friendlyChallengeWidget` attribute. 

It could look something like this:
js
function getWidgetInstanceById(elementId) {
    const element = document.getElementById(elementId);
    if (element) {
        return element.friendlyChallengeWidget;
    } else {
        return null;
    }
}

Credits: merlinfuchs
