### ISSUE TITLE
Suggestion: Optimization for small screens

### ISSUE THREAD

**Issue by BenjaminVettori** [FriendlyCaptcha/friendly-challenge#85]
I noticed that you generate a fixed width style for the ```frc-captcha``` class with 312 px.

https://github.com/FriendlyCaptcha/friendly-challenge/blob/87282feb6f494a9dfd1fd2378f9abc097411c740/src/styles.css#L20

This is suboptimal for small screens (e.g. on my Galaxy S10e), because this causes that the captcha can extend beyond the containing block. I guess the intention of this style is to avoid that the width spans across the full width. Thus, I fixed this in my Site by replacing the width with a max-width as follows:

```css
.frc-captcha {
  width: auto;
  max-width: 350px;
}
```

Maybe you can come up with a suitable min-width if necessary and replace the width style?

**Comment by gzuidhof** [comment]
This is a great suggestion, we'll pick it up (or of course feel free to contribute if you like!).

I do want to validate it in old browsers before we merge something like this, IE11 and old Safari versions tend to behave rather randomly when it comes to styling. It's OK if it looks bad in IE11, but it should be functional (e.g. nothing overlaps the button).
