### ISSUE TITLE
Possible to release a new npm package version?

### ISSUE THREAD

**Issue by MauriceArikoglu** [FriendlyCaptcha/friendly-challenge#86]
As the title states, the current npm package version 0.9.0 is 5 months old. Is it possible to get a current release on to npm?

**Comment by gzuidhof** [comment]
Hi Maurice, 
I hope to publish a new release this week (or perhaps early next week).

The [current changes in master](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/docs/changelog.md#091) are nothing too big yet (only Swedish translation really).

We are really close to merging #75 (=efficiency improvement in solving the puzzle) and #84 (=Russian translation) and perhaps fix #85 (=scaling on mobile sometimes being wrong) - so I want to hold out just a bit longer :)

**Comment by gzuidhof** [comment]
0.9.1 has now been released :) [Here](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/docs/changelog.md#091) is the changelog :rocket:

**Comment by MauriceArikoglu** [comment]
@gzuidhof nice ty! How is test coverage on the project? Is the version considered backward-compatible? (Especially looking at the change #75)

**Comment by gzuidhof** [comment]
Sorry for the whole story. Tl;dr is that this version and future versions will be backwards compatible (unless you see large warnings in the changelog), and that our testing isn't perfect.

**Comment by MauriceArikoglu** [comment]
@gzuidhof thanks for the whole story!! Good insights. We will still do a thorough testing of our implementation and sadly won't meet the goal of deploying the new version until tomorrow. Next release cycle it is!

One thing about the testing: don't build something into your code attempts to detect testing and reduces security checks. I would probably build one base library without the checks and a mock implementation conforming to the main library's implementation / a library umbrella. Sorry if that's unordered thoughts - typing while walking to the train. We can arrange a call if you want to speak.

Best,
Maurice
