### ISSUE TITLE
Server Support > Clearification

### ISSUE THREAD

**Issue by derHodrig** [FriendlyCaptcha/friendly-challenge#88]
Hello,
I read the docs and if I understand it correctly we are only in the frontend. So we take the solution and send it via post to the API => Okay

But what if we want to secure our Backend API endpoints? We could not create a new user solution and the old one is a duplicate.

How to work with that?

**Comment by gzuidhof** [comment]
Hi @derHodrig!

I'm not 100% sure if I understand the question? This Captcha is for use in a web browser (or within a mobile app, but that also involves opening a web browser inside of it), so it's usually for stuff that users interact with like signing up for a web forum.

That signup form gets submitted to an API endpoint, so it kind of protects it (as it should only allow those submissions whose solution submitted along is verified). Maybe that answers your question, but I might as well be totally understanding it wrong!

**Comment by Fancy11111** [comment]
@derHodrig can you sketch out your process for interacting with the API?

Normally you should let your client generate the solution, when he submits his form data you send the solution string with the rest of the form data to your backend. From there you verify the solution with the FriendlyCaptcha API.

You should not send your verification requests from the frontend, as this exposes your API key, which should be a secret. You should only expose your sitekey to the user.

**Comment by derHodrig** [comment]
Hello, thanks for the fast response.

Currently, we using Google Captcha. We validate in the frontend and in the backend. The aim of the initial implementation was, to avoid bot requests from the web and directly from API. In my opinion, most users will use the Web App, just a few tricksters will "play" with the API. My Project manager wants the security(avoid many bot requests) in the backend(API) too. 
In my opinion, this is useless, since if a bot reaches the API directly, the server needs to take the request anyways correct?
Or is there a chance to avoid bot requests with this captcha in the API context? The App context is clear to me.

If not, I'm fine with closing this issue.

**Comment by gzuidhof** [comment]
It's hard to prevent a request from happening, a captcha helps you filter it pretty quickly before it does anything useful, but the server will still have to handle it.

The only way to prevent a request from happening on your server is to put something in front of your web server so they can intercept the request before it reaches your server. This is usually some sort of anti-bot proxy offering, such as [Datadome](https://datadome.co/). That is a much bigger system though which adds a lot of complexity and privacy implications, but if you are actively seeing huge DDoS attacks then that can be the answer (note it also costs $$$$).

In practice I think for 99.9% of webservers such a proxy setup is not necessary and a captcha will help prevent abuse. Also many websites go for something in the middle by putting Cloudflare in front of their server. Perhaps a useful analogy is that the captcha gives "entrance" tickets to do something with your API, but it wont stop customers from arriving with fake entrance tickets that will still have to be checked.
