### ISSUE TITLE
Freindly captcha errors/conflicts, can anyone help please?

### ISSUE THREAD

**Issue by SE-ATW** [FriendlyCaptcha/friendly-challenge#94]
![image](https://user-images.githubusercontent.com/101880514/159019930-b6c3c96a-f024-42f4-a510-3fbcbbd1c4cc.png)

1. The attached is what I get when I press f12, I am trying to optimise my site in WordPress with AIOSEO and its not working as expected and I think this is causing the issues?

2. FYI I uninstalled Google ReCaptcha but it seems it is still in my site system somewhere?  (My root directory does not have it in plugins)

Many thanks if you can help?

**Comment by merlinfuchs** [comment]
I think these are two separate issues that are most likely no related:
- You website is still trying to load the ReCaptcha code
- Friendly Captcha can't find an element on your website to attach the widget to

**Comment by SE-ATW** [comment]
> You website is still trying to load the ReCaptcha code.

Thanks, any ideas how to stop that as I uninstalled the plug in and I can not see it in my root folder "plugins" anymore?

**Comment by merlinfuchs** [comment]
The only thing that I can tell from taking a quick look at your site is that Contact Form 7 seems to be loading the reCaptcha module. I can't tell you why this is happening tho

I will close this issue as it's not related to Friendly Captcha
